// Code generated by ent, DO NOT EDIT.

package budgetentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/XR-Lee/Gemcp/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLTE(FieldID, id))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v uuid.UUID) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldPublicID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldTenantID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldProjectID, v))
}

// ExperimentID applies equality check predicate on the "experiment_id" field. It's identical to ExperimentIDEQ.
func ExperimentID(v int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldExperimentID, v))
}

// Period applies equality check predicate on the "period" field. It's identical to PeriodEQ.
func Period(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldPeriod, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldKind, v))
}

// AmountMilli applies equality check predicate on the "amount_milli" field. It's identical to AmountMilliEQ.
func AmountMilli(v int64) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldAmountMilli, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldDescription, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldIdempotencyKey, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v uuid.UUID) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v uuid.UUID) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...uuid.UUID) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...uuid.UUID) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v uuid.UUID) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v uuid.UUID) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v uuid.UUID) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v uuid.UUID) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLTE(FieldPublicID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotIn(FieldTenantID, vs...))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotIn(FieldProjectID, vs...))
}

// ExperimentIDEQ applies the EQ predicate on the "experiment_id" field.
func ExperimentIDEQ(v int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldExperimentID, v))
}

// ExperimentIDNEQ applies the NEQ predicate on the "experiment_id" field.
func ExperimentIDNEQ(v int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNEQ(FieldExperimentID, v))
}

// ExperimentIDIn applies the In predicate on the "experiment_id" field.
func ExperimentIDIn(vs ...int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIn(FieldExperimentID, vs...))
}

// ExperimentIDNotIn applies the NotIn predicate on the "experiment_id" field.
func ExperimentIDNotIn(vs ...int) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotIn(FieldExperimentID, vs...))
}

// ExperimentIDIsNil applies the IsNil predicate on the "experiment_id" field.
func ExperimentIDIsNil() predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIsNull(FieldExperimentID))
}

// ExperimentIDNotNil applies the NotNil predicate on the "experiment_id" field.
func ExperimentIDNotNil() predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotNull(FieldExperimentID))
}

// PeriodEQ applies the EQ predicate on the "period" field.
func PeriodEQ(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldPeriod, v))
}

// PeriodNEQ applies the NEQ predicate on the "period" field.
func PeriodNEQ(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNEQ(FieldPeriod, v))
}

// PeriodIn applies the In predicate on the "period" field.
func PeriodIn(vs ...string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIn(FieldPeriod, vs...))
}

// PeriodNotIn applies the NotIn predicate on the "period" field.
func PeriodNotIn(vs ...string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotIn(FieldPeriod, vs...))
}

// PeriodGT applies the GT predicate on the "period" field.
func PeriodGT(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGT(FieldPeriod, v))
}

// PeriodGTE applies the GTE predicate on the "period" field.
func PeriodGTE(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGTE(FieldPeriod, v))
}

// PeriodLT applies the LT predicate on the "period" field.
func PeriodLT(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLT(FieldPeriod, v))
}

// PeriodLTE applies the LTE predicate on the "period" field.
func PeriodLTE(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLTE(FieldPeriod, v))
}

// PeriodContains applies the Contains predicate on the "period" field.
func PeriodContains(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldContains(FieldPeriod, v))
}

// PeriodHasPrefix applies the HasPrefix predicate on the "period" field.
func PeriodHasPrefix(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldHasPrefix(FieldPeriod, v))
}

// PeriodHasSuffix applies the HasSuffix predicate on the "period" field.
func PeriodHasSuffix(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldHasSuffix(FieldPeriod, v))
}

// PeriodEqualFold applies the EqualFold predicate on the "period" field.
func PeriodEqualFold(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEqualFold(FieldPeriod, v))
}

// PeriodContainsFold applies the ContainsFold predicate on the "period" field.
func PeriodContainsFold(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldContainsFold(FieldPeriod, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldContainsFold(FieldKind, v))
}

// AmountMilliEQ applies the EQ predicate on the "amount_milli" field.
func AmountMilliEQ(v int64) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldAmountMilli, v))
}

// AmountMilliNEQ applies the NEQ predicate on the "amount_milli" field.
func AmountMilliNEQ(v int64) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNEQ(FieldAmountMilli, v))
}

// AmountMilliIn applies the In predicate on the "amount_milli" field.
func AmountMilliIn(vs ...int64) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIn(FieldAmountMilli, vs...))
}

// AmountMilliNotIn applies the NotIn predicate on the "amount_milli" field.
func AmountMilliNotIn(vs ...int64) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotIn(FieldAmountMilli, vs...))
}

// AmountMilliGT applies the GT predicate on the "amount_milli" field.
func AmountMilliGT(v int64) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGT(FieldAmountMilli, v))
}

// AmountMilliGTE applies the GTE predicate on the "amount_milli" field.
func AmountMilliGTE(v int64) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGTE(FieldAmountMilli, v))
}

// AmountMilliLT applies the LT predicate on the "amount_milli" field.
func AmountMilliLT(v int64) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLT(FieldAmountMilli, v))
}

// AmountMilliLTE applies the LTE predicate on the "amount_milli" field.
func AmountMilliLTE(v int64) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLTE(FieldAmountMilli, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldContainsFold(FieldDescription, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.BudgetEntry {
	return predicate.BudgetEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.BudgetEntry {
	return predicate.BudgetEntry(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.BudgetEntry {
	return predicate.BudgetEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.BudgetEntry {
	return predicate.BudgetEntry(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExperiment applies the HasEdge predicate on the "experiment" edge.
func HasExperiment() predicate.BudgetEntry {
	return predicate.BudgetEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ExperimentTable, ExperimentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExperimentWith applies the HasEdge predicate on the "experiment" edge with a given conditions (other predicates).
func HasExperimentWith(preds ...predicate.Experiment) predicate.BudgetEntry {
	return predicate.BudgetEntry(func(s *sql.Selector) {
		step := newExperimentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BudgetEntry) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BudgetEntry) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BudgetEntry) predicate.BudgetEntry {
	return predicate.BudgetEntry(sql.NotPredicates(p))
}
