// Code generated by ent, DO NOT EDIT.

package agentenrollment

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the agentenrollment type in the database.
	Label = "agent_enrollment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldCodeHash holds the string denoting the code_hash field in the database.
	FieldCodeHash = "code_hash"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldTokenExpiresInDays holds the string denoting the token_expires_in_days field in the database.
	FieldTokenExpiresInDays = "token_expires_in_days"
	// FieldClaimedAt holds the string denoting the claimed_at field in the database.
	FieldClaimedAt = "claimed_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldAgentTokenID holds the string denoting the agent_token_id field in the database.
	FieldAgentTokenID = "agent_token_id"
	// FieldVerification holds the string denoting the verification field in the database.
	FieldVerification = "verification"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeAgentToken holds the string denoting the agent_token edge name in mutations.
	EdgeAgentToken = "agent_token"
	// Table holds the table name of the agentenrollment in the database.
	Table = "agent_enrollments"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "agent_enrollments"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// AgentTokenTable is the table that holds the agent_token relation/edge.
	AgentTokenTable = "agent_enrollments"
	// AgentTokenInverseTable is the table name for the AgentToken entity.
	// It exists in this package in order to avoid circular dependency with the "agenttoken" package.
	AgentTokenInverseTable = "agent_tokens"
	// AgentTokenColumn is the table column denoting the agent_token relation/edge.
	AgentTokenColumn = "agent_token_id"
)

// Columns holds all SQL columns for agentenrollment fields.
var Columns = []string{
	FieldID,
	FieldPublicID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProjectID,
	FieldLabel,
	FieldCodeHash,
	FieldScopes,
	FieldStatus,
	FieldExpiresAt,
	FieldTokenExpiresInDays,
	FieldClaimedAt,
	FieldCompletedAt,
	FieldAgentTokenID,
	FieldVerification,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPublicID holds the default value on creation for the "public_id" field.
	DefaultPublicID func() uuid.UUID
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// LabelValidator is a validator for the "label" field. It is called by the builders before save.
	LabelValidator func(string) error
	// TokenExpiresInDaysValidator is a validator for the "token_expires_in_days" field. It is called by the builders before save.
	TokenExpiresInDaysValidator func(int) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending   Status = "pending"
	StatusClaimed   Status = "claimed"
	StatusCompleted Status = "completed"
	StatusRevoked   Status = "revoked"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusClaimed, StatusCompleted, StatusRevoked:
		return nil
	default:
		return fmt.Errorf("agentenrollment: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AgentEnrollment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByTokenExpiresInDays orders the results by the token_expires_in_days field.
func ByTokenExpiresInDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenExpiresInDays, opts...).ToFunc()
}

// ByClaimedAt orders the results by the claimed_at field.
func ByClaimedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByAgentTokenID orders the results by the agent_token_id field.
func ByAgentTokenID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentTokenID, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByAgentTokenField orders the results by agent_token field.
func ByAgentTokenField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgentTokenStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newAgentTokenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgentTokenInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AgentTokenTable, AgentTokenColumn),
	)
}
