// Code generated by ent, DO NOT EDIT.

package idempotencyrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the idempotencyrecord type in the database.
	Label = "idempotency_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldAgentTokenID holds the string denoting the agent_token_id field in the database.
	FieldAgentTokenID = "agent_token_id"
	// FieldExperimentID holds the string denoting the experiment_id field in the database.
	FieldExperimentID = "experiment_id"
	// FieldKeyHash holds the string denoting the key_hash field in the database.
	FieldKeyHash = "key_hash"
	// FieldRequestFingerprint holds the string denoting the request_fingerprint field in the database.
	FieldRequestFingerprint = "request_fingerprint"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeAgentToken holds the string denoting the agent_token edge name in mutations.
	EdgeAgentToken = "agent_token"
	// EdgeExperiment holds the string denoting the experiment edge name in mutations.
	EdgeExperiment = "experiment"
	// Table holds the table name of the idempotencyrecord in the database.
	Table = "idempotency_records"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "idempotency_records"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// AgentTokenTable is the table that holds the agent_token relation/edge.
	AgentTokenTable = "idempotency_records"
	// AgentTokenInverseTable is the table name for the AgentToken entity.
	// It exists in this package in order to avoid circular dependency with the "agenttoken" package.
	AgentTokenInverseTable = "agent_tokens"
	// AgentTokenColumn is the table column denoting the agent_token relation/edge.
	AgentTokenColumn = "agent_token_id"
	// ExperimentTable is the table that holds the experiment relation/edge.
	ExperimentTable = "idempotency_records"
	// ExperimentInverseTable is the table name for the Experiment entity.
	// It exists in this package in order to avoid circular dependency with the "experiment" package.
	ExperimentInverseTable = "experiments"
	// ExperimentColumn is the table column denoting the experiment relation/edge.
	ExperimentColumn = "experiment_id"
)

// Columns holds all SQL columns for idempotencyrecord fields.
var Columns = []string{
	FieldID,
	FieldPublicID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTenantID,
	FieldAgentTokenID,
	FieldExperimentID,
	FieldKeyHash,
	FieldRequestFingerprint,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPublicID holds the default value on creation for the "public_id" field.
	DefaultPublicID func() uuid.UUID
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the IdempotencyRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByAgentTokenID orders the results by the agent_token_id field.
func ByAgentTokenID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentTokenID, opts...).ToFunc()
}

// ByExperimentID orders the results by the experiment_id field.
func ByExperimentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExperimentID, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByAgentTokenField orders the results by agent_token field.
func ByAgentTokenField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgentTokenStep(), sql.OrderByField(field, opts...))
	}
}

// ByExperimentField orders the results by experiment field.
func ByExperimentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExperimentStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newAgentTokenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgentTokenInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AgentTokenTable, AgentTokenColumn),
	)
}
func newExperimentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExperimentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ExperimentTable, ExperimentColumn),
	)
}
