// Code generated by ent, DO NOT EDIT.

package project

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/XR-Lee/Gemcp/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldID, id))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldPublicID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTenantID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldSlug, v))
}

// MonthlyBudgetMilli applies equality check predicate on the "monthly_budget_milli" field. It's identical to MonthlyBudgetMilliEQ.
func MonthlyBudgetMilli(v int64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldMonthlyBudgetMilli, v))
}

// MaxExperimentMilli applies equality check predicate on the "max_experiment_milli" field. It's identical to MaxExperimentMilliEQ.
func MaxExperimentMilli(v int64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldMaxExperimentMilli, v))
}

// MaxConcurrency applies equality check predicate on the "max_concurrency" field. It's identical to MaxConcurrencyEQ.
func MaxConcurrency(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldMaxConcurrency, v))
}

// MaxRuntimeSeconds applies equality check predicate on the "max_runtime_seconds" field. It's identical to MaxRuntimeSecondsEQ.
func MaxRuntimeSeconds(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldMaxRuntimeSeconds, v))
}

// TimeoutExtensionSeconds applies equality check predicate on the "timeout_extension_seconds" field. It's identical to TimeoutExtensionSecondsEQ.
func TimeoutExtensionSeconds(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTimeoutExtensionSeconds, v))
}

// TerminationGraceSeconds applies equality check predicate on the "termination_grace_seconds" field. It's identical to TerminationGraceSecondsEQ.
func TerminationGraceSeconds(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTerminationGraceSeconds, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTimezone, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldPublicID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldTenantID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldSlug, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldStatus, vs...))
}

// MonthlyBudgetMilliEQ applies the EQ predicate on the "monthly_budget_milli" field.
func MonthlyBudgetMilliEQ(v int64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldMonthlyBudgetMilli, v))
}

// MonthlyBudgetMilliNEQ applies the NEQ predicate on the "monthly_budget_milli" field.
func MonthlyBudgetMilliNEQ(v int64) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldMonthlyBudgetMilli, v))
}

// MonthlyBudgetMilliIn applies the In predicate on the "monthly_budget_milli" field.
func MonthlyBudgetMilliIn(vs ...int64) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldMonthlyBudgetMilli, vs...))
}

// MonthlyBudgetMilliNotIn applies the NotIn predicate on the "monthly_budget_milli" field.
func MonthlyBudgetMilliNotIn(vs ...int64) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldMonthlyBudgetMilli, vs...))
}

// MonthlyBudgetMilliGT applies the GT predicate on the "monthly_budget_milli" field.
func MonthlyBudgetMilliGT(v int64) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldMonthlyBudgetMilli, v))
}

// MonthlyBudgetMilliGTE applies the GTE predicate on the "monthly_budget_milli" field.
func MonthlyBudgetMilliGTE(v int64) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldMonthlyBudgetMilli, v))
}

// MonthlyBudgetMilliLT applies the LT predicate on the "monthly_budget_milli" field.
func MonthlyBudgetMilliLT(v int64) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldMonthlyBudgetMilli, v))
}

// MonthlyBudgetMilliLTE applies the LTE predicate on the "monthly_budget_milli" field.
func MonthlyBudgetMilliLTE(v int64) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldMonthlyBudgetMilli, v))
}

// MaxExperimentMilliEQ applies the EQ predicate on the "max_experiment_milli" field.
func MaxExperimentMilliEQ(v int64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldMaxExperimentMilli, v))
}

// MaxExperimentMilliNEQ applies the NEQ predicate on the "max_experiment_milli" field.
func MaxExperimentMilliNEQ(v int64) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldMaxExperimentMilli, v))
}

// MaxExperimentMilliIn applies the In predicate on the "max_experiment_milli" field.
func MaxExperimentMilliIn(vs ...int64) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldMaxExperimentMilli, vs...))
}

// MaxExperimentMilliNotIn applies the NotIn predicate on the "max_experiment_milli" field.
func MaxExperimentMilliNotIn(vs ...int64) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldMaxExperimentMilli, vs...))
}

// MaxExperimentMilliGT applies the GT predicate on the "max_experiment_milli" field.
func MaxExperimentMilliGT(v int64) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldMaxExperimentMilli, v))
}

// MaxExperimentMilliGTE applies the GTE predicate on the "max_experiment_milli" field.
func MaxExperimentMilliGTE(v int64) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldMaxExperimentMilli, v))
}

// MaxExperimentMilliLT applies the LT predicate on the "max_experiment_milli" field.
func MaxExperimentMilliLT(v int64) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldMaxExperimentMilli, v))
}

// MaxExperimentMilliLTE applies the LTE predicate on the "max_experiment_milli" field.
func MaxExperimentMilliLTE(v int64) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldMaxExperimentMilli, v))
}

// MaxConcurrencyEQ applies the EQ predicate on the "max_concurrency" field.
func MaxConcurrencyEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyNEQ applies the NEQ predicate on the "max_concurrency" field.
func MaxConcurrencyNEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyIn applies the In predicate on the "max_concurrency" field.
func MaxConcurrencyIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyNotIn applies the NotIn predicate on the "max_concurrency" field.
func MaxConcurrencyNotIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyGT applies the GT predicate on the "max_concurrency" field.
func MaxConcurrencyGT(v int) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldMaxConcurrency, v))
}

// MaxConcurrencyGTE applies the GTE predicate on the "max_concurrency" field.
func MaxConcurrencyGTE(v int) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldMaxConcurrency, v))
}

// MaxConcurrencyLT applies the LT predicate on the "max_concurrency" field.
func MaxConcurrencyLT(v int) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldMaxConcurrency, v))
}

// MaxConcurrencyLTE applies the LTE predicate on the "max_concurrency" field.
func MaxConcurrencyLTE(v int) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldMaxConcurrency, v))
}

// MaxRuntimeSecondsEQ applies the EQ predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldMaxRuntimeSeconds, v))
}

// MaxRuntimeSecondsNEQ applies the NEQ predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsNEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldMaxRuntimeSeconds, v))
}

// MaxRuntimeSecondsIn applies the In predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldMaxRuntimeSeconds, vs...))
}

// MaxRuntimeSecondsNotIn applies the NotIn predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsNotIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldMaxRuntimeSeconds, vs...))
}

// MaxRuntimeSecondsGT applies the GT predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsGT(v int) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldMaxRuntimeSeconds, v))
}

// MaxRuntimeSecondsGTE applies the GTE predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsGTE(v int) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldMaxRuntimeSeconds, v))
}

// MaxRuntimeSecondsLT applies the LT predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsLT(v int) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldMaxRuntimeSeconds, v))
}

// MaxRuntimeSecondsLTE applies the LTE predicate on the "max_runtime_seconds" field.
func MaxRuntimeSecondsLTE(v int) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldMaxRuntimeSeconds, v))
}

// TimeoutExtensionSecondsEQ applies the EQ predicate on the "timeout_extension_seconds" field.
func TimeoutExtensionSecondsEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTimeoutExtensionSeconds, v))
}

// TimeoutExtensionSecondsNEQ applies the NEQ predicate on the "timeout_extension_seconds" field.
func TimeoutExtensionSecondsNEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldTimeoutExtensionSeconds, v))
}

// TimeoutExtensionSecondsIn applies the In predicate on the "timeout_extension_seconds" field.
func TimeoutExtensionSecondsIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldTimeoutExtensionSeconds, vs...))
}

// TimeoutExtensionSecondsNotIn applies the NotIn predicate on the "timeout_extension_seconds" field.
func TimeoutExtensionSecondsNotIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldTimeoutExtensionSeconds, vs...))
}

// TimeoutExtensionSecondsGT applies the GT predicate on the "timeout_extension_seconds" field.
func TimeoutExtensionSecondsGT(v int) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldTimeoutExtensionSeconds, v))
}

// TimeoutExtensionSecondsGTE applies the GTE predicate on the "timeout_extension_seconds" field.
func TimeoutExtensionSecondsGTE(v int) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldTimeoutExtensionSeconds, v))
}

// TimeoutExtensionSecondsLT applies the LT predicate on the "timeout_extension_seconds" field.
func TimeoutExtensionSecondsLT(v int) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldTimeoutExtensionSeconds, v))
}

// TimeoutExtensionSecondsLTE applies the LTE predicate on the "timeout_extension_seconds" field.
func TimeoutExtensionSecondsLTE(v int) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldTimeoutExtensionSeconds, v))
}

// TerminationGraceSecondsEQ applies the EQ predicate on the "termination_grace_seconds" field.
func TerminationGraceSecondsEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTerminationGraceSeconds, v))
}

// TerminationGraceSecondsNEQ applies the NEQ predicate on the "termination_grace_seconds" field.
func TerminationGraceSecondsNEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldTerminationGraceSeconds, v))
}

// TerminationGraceSecondsIn applies the In predicate on the "termination_grace_seconds" field.
func TerminationGraceSecondsIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldTerminationGraceSeconds, vs...))
}

// TerminationGraceSecondsNotIn applies the NotIn predicate on the "termination_grace_seconds" field.
func TerminationGraceSecondsNotIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldTerminationGraceSeconds, vs...))
}

// TerminationGraceSecondsGT applies the GT predicate on the "termination_grace_seconds" field.
func TerminationGraceSecondsGT(v int) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldTerminationGraceSeconds, v))
}

// TerminationGraceSecondsGTE applies the GTE predicate on the "termination_grace_seconds" field.
func TerminationGraceSecondsGTE(v int) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldTerminationGraceSeconds, v))
}

// TerminationGraceSecondsLT applies the LT predicate on the "termination_grace_seconds" field.
func TerminationGraceSecondsLT(v int) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldTerminationGraceSeconds, v))
}

// TerminationGraceSecondsLTE applies the LTE predicate on the "termination_grace_seconds" field.
func TerminationGraceSecondsLTE(v int) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldTerminationGraceSeconds, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldTimezone, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEnvironments applies the HasEdge predicate on the "environments" edge.
func HasEnvironments() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EnvironmentsTable, EnvironmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEnvironmentsWith applies the HasEdge predicate on the "environments" edge with a given conditions (other predicates).
func HasEnvironmentsWith(preds ...predicate.Environment) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newEnvironmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResourceProfiles applies the HasEdge predicate on the "resource_profiles" edge.
func HasResourceProfiles() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResourceProfilesTable, ResourceProfilesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResourceProfilesWith applies the HasEdge predicate on the "resource_profiles" edge with a given conditions (other predicates).
func HasResourceProfilesWith(preds ...predicate.ResourceProfile) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newResourceProfilesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRepositories applies the HasEdge predicate on the "repositories" edge.
func HasRepositories() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RepositoriesTable, RepositoriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRepositoriesWith applies the HasEdge predicate on the "repositories" edge with a given conditions (other predicates).
func HasRepositoriesWith(preds ...predicate.Repository) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newRepositoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentTokens applies the HasEdge predicate on the "agent_tokens" edge.
func HasAgentTokens() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AgentTokensTable, AgentTokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentTokensWith applies the HasEdge predicate on the "agent_tokens" edge with a given conditions (other predicates).
func HasAgentTokensWith(preds ...predicate.AgentToken) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newAgentTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentEnrollments applies the HasEdge predicate on the "agent_enrollments" edge.
func HasAgentEnrollments() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AgentEnrollmentsTable, AgentEnrollmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentEnrollmentsWith applies the HasEdge predicate on the "agent_enrollments" edge with a given conditions (other predicates).
func HasAgentEnrollmentsWith(preds ...predicate.AgentEnrollment) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newAgentEnrollmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExperiments applies the HasEdge predicate on the "experiments" edge.
func HasExperiments() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExperimentsTable, ExperimentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExperimentsWith applies the HasEdge predicate on the "experiments" edge with a given conditions (other predicates).
func HasExperimentsWith(preds ...predicate.Experiment) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newExperimentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttempts applies the HasEdge predicate on the "attempts" edge.
func HasAttempts() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttemptsTable, AttemptsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttemptsWith applies the HasEdge predicate on the "attempts" edge with a given conditions (other predicates).
func HasAttemptsWith(preds ...predicate.Attempt) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newAttemptsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProviderResources applies the HasEdge predicate on the "provider_resources" edge.
func HasProviderResources() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProviderResourcesTable, ProviderResourcesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderResourcesWith applies the HasEdge predicate on the "provider_resources" edge with a given conditions (other predicates).
func HasProviderResourcesWith(preds ...predicate.ProviderResource) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newProviderResourcesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBudgetEntries applies the HasEdge predicate on the "budget_entries" edge.
func HasBudgetEntries() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BudgetEntriesTable, BudgetEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBudgetEntriesWith applies the HasEdge predicate on the "budget_entries" edge with a given conditions (other predicates).
func HasBudgetEntriesWith(preds ...predicate.BudgetEntry) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newBudgetEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNodeAccess applies the HasEdge predicate on the "node_access" edge.
func HasNodeAccess() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NodeAccessTable, NodeAccessColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeAccessWith applies the HasEdge predicate on the "node_access" edge with a given conditions (other predicates).
func HasNodeAccessWith(preds ...predicate.NodeProjectAccess) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newNodeAccessStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNodeAssignments applies the HasEdge predicate on the "node_assignments" edge.
func HasNodeAssignments() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NodeAssignmentsTable, NodeAssignmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeAssignmentsWith applies the HasEdge predicate on the "node_assignments" edge with a given conditions (other predicates).
func HasNodeAssignmentsWith(preds ...predicate.NodeAssignment) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newNodeAssignmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCloudSSHAccess applies the HasEdge predicate on the "cloud_ssh_access" edge.
func HasCloudSSHAccess() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CloudSSHAccessTable, CloudSSHAccessColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCloudSSHAccessWith applies the HasEdge predicate on the "cloud_ssh_access" edge with a given conditions (other predicates).
func HasCloudSSHAccessWith(preds ...predicate.CloudSSHProjectAccess) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newCloudSSHAccessStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCloudSSHAssignments applies the HasEdge predicate on the "cloud_ssh_assignments" edge.
func HasCloudSSHAssignments() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CloudSSHAssignmentsTable, CloudSSHAssignmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCloudSSHAssignmentsWith applies the HasEdge predicate on the "cloud_ssh_assignments" edge with a given conditions (other predicates).
func HasCloudSSHAssignmentsWith(preds ...predicate.CloudSSHAssignment) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newCloudSSHAssignmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDiagnosticRuns applies the HasEdge predicate on the "diagnostic_runs" edge.
func HasDiagnosticRuns() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DiagnosticRunsTable, DiagnosticRunsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDiagnosticRunsWith applies the HasEdge predicate on the "diagnostic_runs" edge with a given conditions (other predicates).
func HasDiagnosticRunsWith(preds ...predicate.DiagnosticRun) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newDiagnosticRunsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasImageBakes applies the HasEdge predicate on the "image_bakes" edge.
func HasImageBakes() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ImageBakesTable, ImageBakesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasImageBakesWith applies the HasEdge predicate on the "image_bakes" edge with a given conditions (other predicates).
func HasImageBakesWith(preds ...predicate.ImageBake) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newImageBakesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExperimentProposals applies the HasEdge predicate on the "experiment_proposals" edge.
func HasExperimentProposals() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExperimentProposalsTable, ExperimentProposalsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExperimentProposalsWith applies the HasEdge predicate on the "experiment_proposals" edge with a given conditions (other predicates).
func HasExperimentProposalsWith(preds ...predicate.ExperimentProposal) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newExperimentProposalsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkspaceDatasets applies the HasEdge predicate on the "workspace_datasets" edge.
func HasWorkspaceDatasets() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WorkspaceDatasetsTable, WorkspaceDatasetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspaceDatasetsWith applies the HasEdge predicate on the "workspace_datasets" edge with a given conditions (other predicates).
func HasWorkspaceDatasetsWith(preds ...predicate.WorkspaceDataset) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newWorkspaceDatasetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDatasetBindings applies the HasEdge predicate on the "dataset_bindings" edge.
func HasDatasetBindings() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DatasetBindingsTable, DatasetBindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDatasetBindingsWith applies the HasEdge predicate on the "dataset_bindings" edge with a given conditions (other predicates).
func HasDatasetBindingsWith(preds ...predicate.DatasetBinding) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newDatasetBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStudies applies the HasEdge predicate on the "studies" edge.
func HasStudies() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StudiesTable, StudiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStudiesWith applies the HasEdge predicate on the "studies" edge with a given conditions (other predicates).
func HasStudiesWith(preds ...predicate.Study) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newStudiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIterationPlans applies the HasEdge predicate on the "iteration_plans" edge.
func HasIterationPlans() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IterationPlansTable, IterationPlansColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIterationPlansWith applies the HasEdge predicate on the "iteration_plans" edge with a given conditions (other predicates).
func HasIterationPlansWith(preds ...predicate.IterationPlan) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newIterationPlansStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResearchNodes applies the HasEdge predicate on the "research_nodes" edge.
func HasResearchNodes() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResearchNodesTable, ResearchNodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResearchNodesWith applies the HasEdge predicate on the "research_nodes" edge with a given conditions (other predicates).
func HasResearchNodesWith(preds ...predicate.ResearchNode) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newResearchNodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResearchEdges applies the HasEdge predicate on the "research_edges" edge.
func HasResearchEdges() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResearchEdgesTable, ResearchEdgesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResearchEdgesWith applies the HasEdge predicate on the "research_edges" edge with a given conditions (other predicates).
func HasResearchEdgesWith(preds ...predicate.ResearchEdge) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newResearchEdgesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExperimentCatalogRows applies the HasEdge predicate on the "experiment_catalog_rows" edge.
func HasExperimentCatalogRows() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExperimentCatalogRowsTable, ExperimentCatalogRowsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExperimentCatalogRowsWith applies the HasEdge predicate on the "experiment_catalog_rows" edge with a given conditions (other predicates).
func HasExperimentCatalogRowsWith(preds ...predicate.ExperimentCatalogRow) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newExperimentCatalogRowsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Project) predicate.Project {
	return predicate.Project(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Project) predicate.Project {
	return predicate.Project(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Project) predicate.Project {
	return predicate.Project(sql.NotPredicates(p))
}
