// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/XR-Lee/Gemcp/ent/agentenrollment"
	"github.com/XR-Lee/Gemcp/ent/agenttoken"
	"github.com/XR-Lee/Gemcp/ent/project"
	"github.com/google/uuid"
)

// AgentEnrollment is the model entity for the AgentEnrollment schema.
type AgentEnrollment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID uuid.UUID `json:"public_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID int `json:"project_id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// CodeHash holds the value of the "code_hash" field.
	CodeHash []byte `json:"-"`
	// Scopes holds the value of the "scopes" field.
	Scopes []string `json:"scopes,omitempty"`
	// Status holds the value of the "status" field.
	Status agentenrollment.Status `json:"status,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// TokenExpiresInDays holds the value of the "token_expires_in_days" field.
	TokenExpiresInDays *int `json:"token_expires_in_days,omitempty"`
	// ClaimedAt holds the value of the "claimed_at" field.
	ClaimedAt *time.Time `json:"claimed_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// AgentTokenID holds the value of the "agent_token_id" field.
	AgentTokenID *int `json:"agent_token_id,omitempty"`
	// Verification holds the value of the "verification" field.
	Verification map[string]interface{} `json:"verification,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentEnrollmentQuery when eager-loading is set.
	Edges        AgentEnrollmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentEnrollmentEdges holds the relations/edges for other nodes in the graph.
type AgentEnrollmentEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// AgentToken holds the value of the agent_token edge.
	AgentToken *AgentToken `json:"agent_token,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentEnrollmentEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// AgentTokenOrErr returns the AgentToken value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentEnrollmentEdges) AgentTokenOrErr() (*AgentToken, error) {
	if e.AgentToken != nil {
		return e.AgentToken, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: agenttoken.Label}
	}
	return nil, &NotLoadedError{edge: "agent_token"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentEnrollment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentenrollment.FieldCodeHash, agentenrollment.FieldScopes, agentenrollment.FieldVerification:
			values[i] = new([]byte)
		case agentenrollment.FieldID, agentenrollment.FieldProjectID, agentenrollment.FieldTokenExpiresInDays, agentenrollment.FieldAgentTokenID:
			values[i] = new(sql.NullInt64)
		case agentenrollment.FieldLabel, agentenrollment.FieldStatus:
			values[i] = new(sql.NullString)
		case agentenrollment.FieldCreatedAt, agentenrollment.FieldUpdatedAt, agentenrollment.FieldExpiresAt, agentenrollment.FieldClaimedAt, agentenrollment.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case agentenrollment.FieldPublicID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentEnrollment fields.
func (_m *AgentEnrollment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentenrollment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case agentenrollment.FieldPublicID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value != nil {
				_m.PublicID = *value
			}
		case agentenrollment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case agentenrollment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case agentenrollment.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case agentenrollment.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case agentenrollment.FieldCodeHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field code_hash", values[i])
			} else if value != nil {
				_m.CodeHash = *value
			}
		case agentenrollment.FieldScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Scopes); err != nil {
					return fmt.Errorf("unmarshal field scopes: %w", err)
				}
			}
		case agentenrollment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = agentenrollment.Status(value.String)
			}
		case agentenrollment.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case agentenrollment.FieldTokenExpiresInDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_expires_in_days", values[i])
			} else if value.Valid {
				_m.TokenExpiresInDays = new(int)
				*_m.TokenExpiresInDays = int(value.Int64)
			}
		case agentenrollment.FieldClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field claimed_at", values[i])
			} else if value.Valid {
				_m.ClaimedAt = new(time.Time)
				*_m.ClaimedAt = value.Time
			}
		case agentenrollment.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case agentenrollment.FieldAgentTokenID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field agent_token_id", values[i])
			} else if value.Valid {
				_m.AgentTokenID = new(int)
				*_m.AgentTokenID = int(value.Int64)
			}
		case agentenrollment.FieldVerification:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field verification", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Verification); err != nil {
					return fmt.Errorf("unmarshal field verification: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentEnrollment.
// This includes values selected through modifiers, order, etc.
func (_m *AgentEnrollment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the AgentEnrollment entity.
func (_m *AgentEnrollment) QueryProject() *ProjectQuery {
	return NewAgentEnrollmentClient(_m.config).QueryProject(_m)
}

// QueryAgentToken queries the "agent_token" edge of the AgentEnrollment entity.
func (_m *AgentEnrollment) QueryAgentToken() *AgentTokenQuery {
	return NewAgentEnrollmentClient(_m.config).QueryAgentToken(_m)
}

// Update returns a builder for updating this AgentEnrollment.
// Note that you need to call AgentEnrollment.Unwrap() before calling this method if this AgentEnrollment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentEnrollment) Update() *AgentEnrollmentUpdateOne {
	return NewAgentEnrollmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentEnrollment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentEnrollment) Unwrap() *AgentEnrollment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentEnrollment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentEnrollment) String() string {
	var builder strings.Builder
	builder.WriteString("AgentEnrollment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("public_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("code_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scopes))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.TokenExpiresInDays; v != nil {
		builder.WriteString("token_expires_in_days=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ClaimedAt; v != nil {
		builder.WriteString("claimed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AgentTokenID; v != nil {
		builder.WriteString("agent_token_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("verification=")
	builder.WriteString(fmt.Sprintf("%v", _m.Verification))
	builder.WriteByte(')')
	return builder.String()
}

// AgentEnrollments is a parsable slice of AgentEnrollment.
type AgentEnrollments []*AgentEnrollment
