// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/XR-Lee/Gemcp/ent/agentenrollment"
	"github.com/XR-Lee/Gemcp/ent/predicate"
)

// AgentEnrollmentDelete is the builder for deleting a AgentEnrollment entity.
type AgentEnrollmentDelete struct {
	config
	hooks    []Hook
	mutation *AgentEnrollmentMutation
}

// Where appends a list predicates to the AgentEnrollmentDelete builder.
func (_d *AgentEnrollmentDelete) Where(ps ...predicate.AgentEnrollment) *AgentEnrollmentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AgentEnrollmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentEnrollmentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AgentEnrollmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(agentenrollment.Table, sqlgraph.NewFieldSpec(agentenrollment.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AgentEnrollmentDeleteOne is the builder for deleting a single AgentEnrollment entity.
type AgentEnrollmentDeleteOne struct {
	_d *AgentEnrollmentDelete
}

// Where appends a list predicates to the AgentEnrollmentDelete builder.
func (_d *AgentEnrollmentDeleteOne) Where(ps ...predicate.AgentEnrollment) *AgentEnrollmentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AgentEnrollmentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{agentenrollment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentEnrollmentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
