// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/XR-Lee/Gemcp/ent/agenttoken"
	"github.com/XR-Lee/Gemcp/ent/predicate"
)

// AgentTokenUpdate is the builder for updating AgentToken entities.
type AgentTokenUpdate struct {
	config
	hooks    []Hook
	mutation *AgentTokenMutation
}

// Where appends a list predicates to the AgentTokenUpdate builder.
func (_u *AgentTokenUpdate) Where(ps ...predicate.AgentToken) *AgentTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentTokenUpdate) SetUpdatedAt(v time.Time) *AgentTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *AgentTokenUpdate) SetLabel(v string) *AgentTokenUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *AgentTokenUpdate) SetNillableLabel(v *string) *AgentTokenUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *AgentTokenUpdate) SetPrefix(v string) *AgentTokenUpdate {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *AgentTokenUpdate) SetNillablePrefix(v *string) *AgentTokenUpdate {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *AgentTokenUpdate) SetTokenHash(v []byte) *AgentTokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetPrincipalType sets the "principal_type" field.
func (_u *AgentTokenUpdate) SetPrincipalType(v agenttoken.PrincipalType) *AgentTokenUpdate {
	_u.mutation.SetPrincipalType(v)
	return _u
}

// SetNillablePrincipalType sets the "principal_type" field if the given value is not nil.
func (_u *AgentTokenUpdate) SetNillablePrincipalType(v *agenttoken.PrincipalType) *AgentTokenUpdate {
	if v != nil {
		_u.SetPrincipalType(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AgentTokenUpdate) SetScopes(v []string) *AgentTokenUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AgentTokenUpdate) AppendScopes(v []string) *AgentTokenUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentTokenUpdate) SetStatus(v agenttoken.Status) *AgentTokenUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentTokenUpdate) SetNillableStatus(v *agenttoken.Status) *AgentTokenUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AgentTokenUpdate) SetExpiresAt(v time.Time) *AgentTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AgentTokenUpdate) SetNillableExpiresAt(v *time.Time) *AgentTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AgentTokenUpdate) ClearExpiresAt() *AgentTokenUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AgentTokenUpdate) SetLastUsedAt(v time.Time) *AgentTokenUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AgentTokenUpdate) SetNillableLastUsedAt(v *time.Time) *AgentTokenUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AgentTokenUpdate) ClearLastUsedAt() *AgentTokenUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// Mutation returns the AgentTokenMutation object of the builder.
func (_u *AgentTokenUpdate) Mutation() *AgentTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agenttoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentTokenUpdate) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := agenttoken.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "AgentToken.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prefix(); ok {
		if err := agenttoken.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "AgentToken.prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrincipalType(); ok {
		if err := agenttoken.PrincipalTypeValidator(v); err != nil {
			return &ValidationError{Name: "principal_type", err: fmt.Errorf(`ent: validator failed for field "AgentToken.principal_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agenttoken.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentToken.status": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentToken.project"`)
	}
	return nil
}

func (_u *AgentTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenttoken.Table, agenttoken.Columns, sqlgraph.NewFieldSpec(agenttoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agenttoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(agenttoken.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(agenttoken.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(agenttoken.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.PrincipalType(); ok {
		_spec.SetField(agenttoken.FieldPrincipalType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(agenttoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agenttoken.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agenttoken.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(agenttoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(agenttoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(agenttoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(agenttoken.FieldLastUsedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenttoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentTokenUpdateOne is the builder for updating a single AgentToken entity.
type AgentTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentTokenMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentTokenUpdateOne) SetUpdatedAt(v time.Time) *AgentTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *AgentTokenUpdateOne) SetLabel(v string) *AgentTokenUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *AgentTokenUpdateOne) SetNillableLabel(v *string) *AgentTokenUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *AgentTokenUpdateOne) SetPrefix(v string) *AgentTokenUpdateOne {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *AgentTokenUpdateOne) SetNillablePrefix(v *string) *AgentTokenUpdateOne {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *AgentTokenUpdateOne) SetTokenHash(v []byte) *AgentTokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetPrincipalType sets the "principal_type" field.
func (_u *AgentTokenUpdateOne) SetPrincipalType(v agenttoken.PrincipalType) *AgentTokenUpdateOne {
	_u.mutation.SetPrincipalType(v)
	return _u
}

// SetNillablePrincipalType sets the "principal_type" field if the given value is not nil.
func (_u *AgentTokenUpdateOne) SetNillablePrincipalType(v *agenttoken.PrincipalType) *AgentTokenUpdateOne {
	if v != nil {
		_u.SetPrincipalType(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AgentTokenUpdateOne) SetScopes(v []string) *AgentTokenUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AgentTokenUpdateOne) AppendScopes(v []string) *AgentTokenUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentTokenUpdateOne) SetStatus(v agenttoken.Status) *AgentTokenUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentTokenUpdateOne) SetNillableStatus(v *agenttoken.Status) *AgentTokenUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AgentTokenUpdateOne) SetExpiresAt(v time.Time) *AgentTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AgentTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *AgentTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AgentTokenUpdateOne) ClearExpiresAt() *AgentTokenUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AgentTokenUpdateOne) SetLastUsedAt(v time.Time) *AgentTokenUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AgentTokenUpdateOne) SetNillableLastUsedAt(v *time.Time) *AgentTokenUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AgentTokenUpdateOne) ClearLastUsedAt() *AgentTokenUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// Mutation returns the AgentTokenMutation object of the builder.
func (_u *AgentTokenUpdateOne) Mutation() *AgentTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the AgentTokenUpdate builder.
func (_u *AgentTokenUpdateOne) Where(ps ...predicate.AgentToken) *AgentTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentTokenUpdateOne) Select(field string, fields ...string) *AgentTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentToken entity.
func (_u *AgentTokenUpdateOne) Save(ctx context.Context) (*AgentToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentTokenUpdateOne) SaveX(ctx context.Context) *AgentToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agenttoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentTokenUpdateOne) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := agenttoken.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "AgentToken.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prefix(); ok {
		if err := agenttoken.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "AgentToken.prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrincipalType(); ok {
		if err := agenttoken.PrincipalTypeValidator(v); err != nil {
			return &ValidationError{Name: "principal_type", err: fmt.Errorf(`ent: validator failed for field "AgentToken.principal_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agenttoken.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentToken.status": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentToken.project"`)
	}
	return nil
}

func (_u *AgentTokenUpdateOne) sqlSave(ctx context.Context) (_node *AgentToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenttoken.Table, agenttoken.Columns, sqlgraph.NewFieldSpec(agenttoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agenttoken.FieldID)
		for _, f := range fields {
			if !agenttoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agenttoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agenttoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(agenttoken.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(agenttoken.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(agenttoken.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.PrincipalType(); ok {
		_spec.SetField(agenttoken.FieldPrincipalType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(agenttoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agenttoken.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agenttoken.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(agenttoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(agenttoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(agenttoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(agenttoken.FieldLastUsedAt, field.TypeTime)
	}
	_node = &AgentToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenttoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
