// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/XR-Lee/Gemcp/ent/attempt"
	"github.com/XR-Lee/Gemcp/ent/experiment"
	"github.com/XR-Lee/Gemcp/ent/project"
	"github.com/XR-Lee/Gemcp/ent/tenant"
	"github.com/google/uuid"
)

// Attempt is the model entity for the Attempt schema.
type Attempt struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID uuid.UUID `json:"public_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int `json:"tenant_id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID int `json:"project_id,omitempty"`
	// ExperimentID holds the value of the "experiment_id" field.
	ExperimentID int `json:"experiment_id,omitempty"`
	// Number holds the value of the "number" field.
	Number int `json:"number,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// ProviderResourceID holds the value of the "provider_resource_id" field.
	ProviderResourceID *string `json:"provider_resource_id,omitempty"`
	// RetryReason holds the value of the "retry_reason" field.
	RetryReason *string `json:"retry_reason,omitempty"`
	// FailureCode holds the value of the "failure_code" field.
	FailureCode *string `json:"failure_code,omitempty"`
	// FailureReason holds the value of the "failure_reason" field.
	FailureReason *string `json:"failure_reason,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// EstimatedCostMilli holds the value of the "estimated_cost_milli" field.
	EstimatedCostMilli int64 `json:"estimated_cost_milli,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AttemptQuery when eager-loading is set.
	Edges        AttemptEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AttemptEdges holds the relations/edges for other nodes in the graph.
type AttemptEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Experiment holds the value of the experiment edge.
	Experiment *Experiment `json:"experiment,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttemptEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttemptEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// ExperimentOrErr returns the Experiment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttemptEdges) ExperimentOrErr() (*Experiment, error) {
	if e.Experiment != nil {
		return e.Experiment, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: experiment.Label}
	}
	return nil, &NotLoadedError{edge: "experiment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Attempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case attempt.FieldID, attempt.FieldTenantID, attempt.FieldProjectID, attempt.FieldExperimentID, attempt.FieldNumber, attempt.FieldEstimatedCostMilli:
			values[i] = new(sql.NullInt64)
		case attempt.FieldState, attempt.FieldProviderResourceID, attempt.FieldRetryReason, attempt.FieldFailureCode, attempt.FieldFailureReason:
			values[i] = new(sql.NullString)
		case attempt.FieldCreatedAt, attempt.FieldUpdatedAt, attempt.FieldStartedAt, attempt.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		case attempt.FieldPublicID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Attempt fields.
func (_m *Attempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case attempt.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case attempt.FieldPublicID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value != nil {
				_m.PublicID = *value
			}
		case attempt.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case attempt.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case attempt.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = int(value.Int64)
			}
		case attempt.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case attempt.FieldExperimentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field experiment_id", values[i])
			} else if value.Valid {
				_m.ExperimentID = int(value.Int64)
			}
		case attempt.FieldNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				_m.Number = int(value.Int64)
			}
		case attempt.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case attempt.FieldProviderResourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_resource_id", values[i])
			} else if value.Valid {
				_m.ProviderResourceID = new(string)
				*_m.ProviderResourceID = value.String
			}
		case attempt.FieldRetryReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field retry_reason", values[i])
			} else if value.Valid {
				_m.RetryReason = new(string)
				*_m.RetryReason = value.String
			}
		case attempt.FieldFailureCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_code", values[i])
			} else if value.Valid {
				_m.FailureCode = new(string)
				*_m.FailureCode = value.String
			}
		case attempt.FieldFailureReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_reason", values[i])
			} else if value.Valid {
				_m.FailureReason = new(string)
				*_m.FailureReason = value.String
			}
		case attempt.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case attempt.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case attempt.FieldEstimatedCostMilli:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_cost_milli", values[i])
			} else if value.Valid {
				_m.EstimatedCostMilli = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Attempt.
// This includes values selected through modifiers, order, etc.
func (_m *Attempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the Attempt entity.
func (_m *Attempt) QueryTenant() *TenantQuery {
	return NewAttemptClient(_m.config).QueryTenant(_m)
}

// QueryProject queries the "project" edge of the Attempt entity.
func (_m *Attempt) QueryProject() *ProjectQuery {
	return NewAttemptClient(_m.config).QueryProject(_m)
}

// QueryExperiment queries the "experiment" edge of the Attempt entity.
func (_m *Attempt) QueryExperiment() *ExperimentQuery {
	return NewAttemptClient(_m.config).QueryExperiment(_m)
}

// Update returns a builder for updating this Attempt.
// Note that you need to call Attempt.Unwrap() before calling this method if this Attempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Attempt) Update() *AttemptUpdateOne {
	return NewAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Attempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Attempt) Unwrap() *Attempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Attempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Attempt) String() string {
	var builder strings.Builder
	builder.WriteString("Attempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("public_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("experiment_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExperimentID))
	builder.WriteString(", ")
	builder.WriteString("number=")
	builder.WriteString(fmt.Sprintf("%v", _m.Number))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	if v := _m.ProviderResourceID; v != nil {
		builder.WriteString("provider_resource_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RetryReason; v != nil {
		builder.WriteString("retry_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FailureCode; v != nil {
		builder.WriteString("failure_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FailureReason; v != nil {
		builder.WriteString("failure_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("estimated_cost_milli=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedCostMilli))
	builder.WriteByte(')')
	return builder.String()
}

// Attempts is a parsable slice of Attempt.
type Attempts []*Attempt
