// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/XR-Lee/Gemcp/ent/datasetbinding"
	"github.com/XR-Lee/Gemcp/ent/predicate"
)

// DatasetBindingDelete is the builder for deleting a DatasetBinding entity.
type DatasetBindingDelete struct {
	config
	hooks    []Hook
	mutation *DatasetBindingMutation
}

// Where appends a list predicates to the DatasetBindingDelete builder.
func (_d *DatasetBindingDelete) Where(ps ...predicate.DatasetBinding) *DatasetBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DatasetBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DatasetBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DatasetBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(datasetbinding.Table, sqlgraph.NewFieldSpec(datasetbinding.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DatasetBindingDeleteOne is the builder for deleting a single DatasetBinding entity.
type DatasetBindingDeleteOne struct {
	_d *DatasetBindingDelete
}

// Where appends a list predicates to the DatasetBindingDelete builder.
func (_d *DatasetBindingDeleteOne) Where(ps ...predicate.DatasetBinding) *DatasetBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DatasetBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{datasetbinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DatasetBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
