// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/XR-Lee/Gemcp/ent/diagnosticrun"
	"github.com/XR-Lee/Gemcp/ent/predicate"
)

// DiagnosticRunUpdate is the builder for updating DiagnosticRun entities.
type DiagnosticRunUpdate struct {
	config
	hooks    []Hook
	mutation *DiagnosticRunMutation
}

// Where appends a list predicates to the DiagnosticRunUpdate builder.
func (_u *DiagnosticRunUpdate) Where(ps ...predicate.DiagnosticRun) *DiagnosticRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DiagnosticRunUpdate) SetUpdatedAt(v time.Time) *DiagnosticRunUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DiagnosticRunMutation object of the builder.
func (_u *DiagnosticRunUpdate) Mutation() *DiagnosticRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiagnosticRunUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiagnosticRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiagnosticRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiagnosticRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DiagnosticRunUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := diagnosticrun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiagnosticRunUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiagnosticRun.tenant"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiagnosticRun.project"`)
	}
	if _u.mutation.ExperimentCleared() && len(_u.mutation.ExperimentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiagnosticRun.experiment"`)
	}
	return nil
}

func (_u *DiagnosticRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(diagnosticrun.Table, diagnosticrun.Columns, sqlgraph.NewFieldSpec(diagnosticrun.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(diagnosticrun.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diagnosticrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiagnosticRunUpdateOne is the builder for updating a single DiagnosticRun entity.
type DiagnosticRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiagnosticRunMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DiagnosticRunUpdateOne) SetUpdatedAt(v time.Time) *DiagnosticRunUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DiagnosticRunMutation object of the builder.
func (_u *DiagnosticRunUpdateOne) Mutation() *DiagnosticRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the DiagnosticRunUpdate builder.
func (_u *DiagnosticRunUpdateOne) Where(ps ...predicate.DiagnosticRun) *DiagnosticRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiagnosticRunUpdateOne) Select(field string, fields ...string) *DiagnosticRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DiagnosticRun entity.
func (_u *DiagnosticRunUpdateOne) Save(ctx context.Context) (*DiagnosticRun, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiagnosticRunUpdateOne) SaveX(ctx context.Context) *DiagnosticRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiagnosticRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiagnosticRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DiagnosticRunUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := diagnosticrun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiagnosticRunUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiagnosticRun.tenant"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiagnosticRun.project"`)
	}
	if _u.mutation.ExperimentCleared() && len(_u.mutation.ExperimentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiagnosticRun.experiment"`)
	}
	return nil
}

func (_u *DiagnosticRunUpdateOne) sqlSave(ctx context.Context) (_node *DiagnosticRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(diagnosticrun.Table, diagnosticrun.Columns, sqlgraph.NewFieldSpec(diagnosticrun.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DiagnosticRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, diagnosticrun.FieldID)
		for _, f := range fields {
			if !diagnosticrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != diagnosticrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(diagnosticrun.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DiagnosticRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diagnosticrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
