// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/XR-Lee/Gemcp/ent/agenttoken"
	"github.com/XR-Lee/Gemcp/ent/environment"
	"github.com/XR-Lee/Gemcp/ent/experiment"
	"github.com/XR-Lee/Gemcp/ent/experimentproposal"
	"github.com/XR-Lee/Gemcp/ent/predicate"
	"github.com/XR-Lee/Gemcp/ent/project"
	"github.com/XR-Lee/Gemcp/ent/repository"
	"github.com/XR-Lee/Gemcp/ent/resourceprofile"
	"github.com/XR-Lee/Gemcp/ent/tenant"
)

// ExperimentProposalQuery is the builder for querying ExperimentProposal entities.
type ExperimentProposalQuery struct {
	config
	ctx                 *QueryContext
	order               []experimentproposal.OrderOption
	inters              []Interceptor
	predicates          []predicate.ExperimentProposal
	withTenant          *TenantQuery
	withProject         *ProjectQuery
	withAgentToken      *AgentTokenQuery
	withRepository      *RepositoryQuery
	withEnvironment     *EnvironmentQuery
	withResourceProfile *ResourceProfileQuery
	withExperiment      *ExperimentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExperimentProposalQuery builder.
func (_q *ExperimentProposalQuery) Where(ps ...predicate.ExperimentProposal) *ExperimentProposalQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ExperimentProposalQuery) Limit(limit int) *ExperimentProposalQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ExperimentProposalQuery) Offset(offset int) *ExperimentProposalQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ExperimentProposalQuery) Unique(unique bool) *ExperimentProposalQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ExperimentProposalQuery) Order(o ...experimentproposal.OrderOption) *ExperimentProposalQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTenant chains the current query on the "tenant" edge.
func (_q *ExperimentProposalQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(experimentproposal.Table, experimentproposal.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, experimentproposal.TenantTable, experimentproposal.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProject chains the current query on the "project" edge.
func (_q *ExperimentProposalQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(experimentproposal.Table, experimentproposal.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, experimentproposal.ProjectTable, experimentproposal.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgentToken chains the current query on the "agent_token" edge.
func (_q *ExperimentProposalQuery) QueryAgentToken() *AgentTokenQuery {
	query := (&AgentTokenClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(experimentproposal.Table, experimentproposal.FieldID, selector),
			sqlgraph.To(agenttoken.Table, agenttoken.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, experimentproposal.AgentTokenTable, experimentproposal.AgentTokenColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRepository chains the current query on the "repository" edge.
func (_q *ExperimentProposalQuery) QueryRepository() *RepositoryQuery {
	query := (&RepositoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(experimentproposal.Table, experimentproposal.FieldID, selector),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, experimentproposal.RepositoryTable, experimentproposal.RepositoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEnvironment chains the current query on the "environment" edge.
func (_q *ExperimentProposalQuery) QueryEnvironment() *EnvironmentQuery {
	query := (&EnvironmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(experimentproposal.Table, experimentproposal.FieldID, selector),
			sqlgraph.To(environment.Table, environment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, experimentproposal.EnvironmentTable, experimentproposal.EnvironmentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryResourceProfile chains the current query on the "resource_profile" edge.
func (_q *ExperimentProposalQuery) QueryResourceProfile() *ResourceProfileQuery {
	query := (&ResourceProfileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(experimentproposal.Table, experimentproposal.FieldID, selector),
			sqlgraph.To(resourceprofile.Table, resourceprofile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, experimentproposal.ResourceProfileTable, experimentproposal.ResourceProfileColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExperiment chains the current query on the "experiment" edge.
func (_q *ExperimentProposalQuery) QueryExperiment() *ExperimentQuery {
	query := (&ExperimentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(experimentproposal.Table, experimentproposal.FieldID, selector),
			sqlgraph.To(experiment.Table, experiment.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, experimentproposal.ExperimentTable, experimentproposal.ExperimentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ExperimentProposal entity from the query.
// Returns a *NotFoundError when no ExperimentProposal was found.
func (_q *ExperimentProposalQuery) First(ctx context.Context) (*ExperimentProposal, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{experimentproposal.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ExperimentProposalQuery) FirstX(ctx context.Context) *ExperimentProposal {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ExperimentProposal ID from the query.
// Returns a *NotFoundError when no ExperimentProposal ID was found.
func (_q *ExperimentProposalQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{experimentproposal.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ExperimentProposalQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ExperimentProposal entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ExperimentProposal entity is found.
// Returns a *NotFoundError when no ExperimentProposal entities are found.
func (_q *ExperimentProposalQuery) Only(ctx context.Context) (*ExperimentProposal, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{experimentproposal.Label}
	default:
		return nil, &NotSingularError{experimentproposal.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ExperimentProposalQuery) OnlyX(ctx context.Context) *ExperimentProposal {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ExperimentProposal ID in the query.
// Returns a *NotSingularError when more than one ExperimentProposal ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ExperimentProposalQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{experimentproposal.Label}
	default:
		err = &NotSingularError{experimentproposal.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ExperimentProposalQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ExperimentProposals.
func (_q *ExperimentProposalQuery) All(ctx context.Context) ([]*ExperimentProposal, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ExperimentProposal, *ExperimentProposalQuery]()
	return withInterceptors[[]*ExperimentProposal](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ExperimentProposalQuery) AllX(ctx context.Context) []*ExperimentProposal {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ExperimentProposal IDs.
func (_q *ExperimentProposalQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(experimentproposal.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ExperimentProposalQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ExperimentProposalQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ExperimentProposalQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ExperimentProposalQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ExperimentProposalQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ExperimentProposalQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExperimentProposalQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ExperimentProposalQuery) Clone() *ExperimentProposalQuery {
	if _q == nil {
		return nil
	}
	return &ExperimentProposalQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]experimentproposal.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.ExperimentProposal{}, _q.predicates...),
		withTenant:          _q.withTenant.Clone(),
		withProject:         _q.withProject.Clone(),
		withAgentToken:      _q.withAgentToken.Clone(),
		withRepository:      _q.withRepository.Clone(),
		withEnvironment:     _q.withEnvironment.Clone(),
		withResourceProfile: _q.withResourceProfile.Clone(),
		withExperiment:      _q.withExperiment.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExperimentProposalQuery) WithTenant(opts ...func(*TenantQuery)) *ExperimentProposalQuery {
	query := (&TenantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenant = query
	return _q
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExperimentProposalQuery) WithProject(opts ...func(*ProjectQuery)) *ExperimentProposalQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithAgentToken tells the query-builder to eager-load the nodes that are connected to
// the "agent_token" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExperimentProposalQuery) WithAgentToken(opts ...func(*AgentTokenQuery)) *ExperimentProposalQuery {
	query := (&AgentTokenClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAgentToken = query
	return _q
}

// WithRepository tells the query-builder to eager-load the nodes that are connected to
// the "repository" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExperimentProposalQuery) WithRepository(opts ...func(*RepositoryQuery)) *ExperimentProposalQuery {
	query := (&RepositoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRepository = query
	return _q
}

// WithEnvironment tells the query-builder to eager-load the nodes that are connected to
// the "environment" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExperimentProposalQuery) WithEnvironment(opts ...func(*EnvironmentQuery)) *ExperimentProposalQuery {
	query := (&EnvironmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEnvironment = query
	return _q
}

// WithResourceProfile tells the query-builder to eager-load the nodes that are connected to
// the "resource_profile" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExperimentProposalQuery) WithResourceProfile(opts ...func(*ResourceProfileQuery)) *ExperimentProposalQuery {
	query := (&ResourceProfileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withResourceProfile = query
	return _q
}

// WithExperiment tells the query-builder to eager-load the nodes that are connected to
// the "experiment" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExperimentProposalQuery) WithExperiment(opts ...func(*ExperimentQuery)) *ExperimentProposalQuery {
	query := (&ExperimentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withExperiment = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PublicID uuid.UUID `json:"public_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ExperimentProposal.Query().
//		GroupBy(experimentproposal.FieldPublicID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ExperimentProposalQuery) GroupBy(field string, fields ...string) *ExperimentProposalGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExperimentProposalGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = experimentproposal.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PublicID uuid.UUID `json:"public_id,omitempty"`
//	}
//
//	client.ExperimentProposal.Query().
//		Select(experimentproposal.FieldPublicID).
//		Scan(ctx, &v)
func (_q *ExperimentProposalQuery) Select(fields ...string) *ExperimentProposalSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ExperimentProposalSelect{ExperimentProposalQuery: _q}
	sbuild.label = experimentproposal.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExperimentProposalSelect configured with the given aggregations.
func (_q *ExperimentProposalQuery) Aggregate(fns ...AggregateFunc) *ExperimentProposalSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ExperimentProposalQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !experimentproposal.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ExperimentProposalQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ExperimentProposal, error) {
	var (
		nodes       = []*ExperimentProposal{}
		_spec       = _q.querySpec()
		loadedTypes = [7]bool{
			_q.withTenant != nil,
			_q.withProject != nil,
			_q.withAgentToken != nil,
			_q.withRepository != nil,
			_q.withEnvironment != nil,
			_q.withResourceProfile != nil,
			_q.withExperiment != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ExperimentProposal).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ExperimentProposal{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTenant; query != nil {
		if err := _q.loadTenant(ctx, query, nodes, nil,
			func(n *ExperimentProposal, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *ExperimentProposal, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAgentToken; query != nil {
		if err := _q.loadAgentToken(ctx, query, nodes, nil,
			func(n *ExperimentProposal, e *AgentToken) { n.Edges.AgentToken = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRepository; query != nil {
		if err := _q.loadRepository(ctx, query, nodes, nil,
			func(n *ExperimentProposal, e *Repository) { n.Edges.Repository = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEnvironment; query != nil {
		if err := _q.loadEnvironment(ctx, query, nodes, nil,
			func(n *ExperimentProposal, e *Environment) { n.Edges.Environment = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withResourceProfile; query != nil {
		if err := _q.loadResourceProfile(ctx, query, nodes, nil,
			func(n *ExperimentProposal, e *ResourceProfile) { n.Edges.ResourceProfile = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withExperiment; query != nil {
		if err := _q.loadExperiment(ctx, query, nodes, nil,
			func(n *ExperimentProposal, e *Experiment) { n.Edges.Experiment = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ExperimentProposalQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*ExperimentProposal, init func(*ExperimentProposal), assign func(*ExperimentProposal, *Tenant)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ExperimentProposal)
	for i := range nodes {
		fk := nodes[i].TenantID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ExperimentProposalQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*ExperimentProposal, init func(*ExperimentProposal), assign func(*ExperimentProposal, *Project)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ExperimentProposal)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ExperimentProposalQuery) loadAgentToken(ctx context.Context, query *AgentTokenQuery, nodes []*ExperimentProposal, init func(*ExperimentProposal), assign func(*ExperimentProposal, *AgentToken)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ExperimentProposal)
	for i := range nodes {
		fk := nodes[i].AgentTokenID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(agenttoken.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "agent_token_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ExperimentProposalQuery) loadRepository(ctx context.Context, query *RepositoryQuery, nodes []*ExperimentProposal, init func(*ExperimentProposal), assign func(*ExperimentProposal, *Repository)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ExperimentProposal)
	for i := range nodes {
		if nodes[i].RepositoryID == nil {
			continue
		}
		fk := *nodes[i].RepositoryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(repository.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "repository_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ExperimentProposalQuery) loadEnvironment(ctx context.Context, query *EnvironmentQuery, nodes []*ExperimentProposal, init func(*ExperimentProposal), assign func(*ExperimentProposal, *Environment)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ExperimentProposal)
	for i := range nodes {
		fk := nodes[i].EnvironmentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(environment.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "environment_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ExperimentProposalQuery) loadResourceProfile(ctx context.Context, query *ResourceProfileQuery, nodes []*ExperimentProposal, init func(*ExperimentProposal), assign func(*ExperimentProposal, *ResourceProfile)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ExperimentProposal)
	for i := range nodes {
		fk := nodes[i].ResourceProfileID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(resourceprofile.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "resource_profile_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ExperimentProposalQuery) loadExperiment(ctx context.Context, query *ExperimentQuery, nodes []*ExperimentProposal, init func(*ExperimentProposal), assign func(*ExperimentProposal, *Experiment)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ExperimentProposal)
	for i := range nodes {
		if nodes[i].ExperimentID == nil {
			continue
		}
		fk := *nodes[i].ExperimentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(experiment.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "experiment_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ExperimentProposalQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ExperimentProposalQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(experimentproposal.Table, experimentproposal.Columns, sqlgraph.NewFieldSpec(experimentproposal.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, experimentproposal.FieldID)
		for i := range fields {
			if fields[i] != experimentproposal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTenant != nil {
			_spec.Node.AddColumnOnce(experimentproposal.FieldTenantID)
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(experimentproposal.FieldProjectID)
		}
		if _q.withAgentToken != nil {
			_spec.Node.AddColumnOnce(experimentproposal.FieldAgentTokenID)
		}
		if _q.withRepository != nil {
			_spec.Node.AddColumnOnce(experimentproposal.FieldRepositoryID)
		}
		if _q.withEnvironment != nil {
			_spec.Node.AddColumnOnce(experimentproposal.FieldEnvironmentID)
		}
		if _q.withResourceProfile != nil {
			_spec.Node.AddColumnOnce(experimentproposal.FieldResourceProfileID)
		}
		if _q.withExperiment != nil {
			_spec.Node.AddColumnOnce(experimentproposal.FieldExperimentID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ExperimentProposalQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(experimentproposal.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = experimentproposal.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ExperimentProposalGroupBy is the group-by builder for ExperimentProposal entities.
type ExperimentProposalGroupBy struct {
	selector
	build *ExperimentProposalQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ExperimentProposalGroupBy) Aggregate(fns ...AggregateFunc) *ExperimentProposalGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ExperimentProposalGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExperimentProposalQuery, *ExperimentProposalGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ExperimentProposalGroupBy) sqlScan(ctx context.Context, root *ExperimentProposalQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExperimentProposalSelect is the builder for selecting fields of ExperimentProposal entities.
type ExperimentProposalSelect struct {
	*ExperimentProposalQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ExperimentProposalSelect) Aggregate(fns ...AggregateFunc) *ExperimentProposalSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ExperimentProposalSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExperimentProposalQuery, *ExperimentProposalSelect](ctx, _s.ExperimentProposalQuery, _s, _s.inters, v)
}

func (_s *ExperimentProposalSelect) sqlScan(ctx context.Context, root *ExperimentProposalQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
