// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/XR-Lee/Gemcp/ent/agenttoken"
	"github.com/XR-Lee/Gemcp/ent/experiment"
	"github.com/XR-Lee/Gemcp/ent/idempotencyrecord"
	"github.com/XR-Lee/Gemcp/ent/tenant"
	"github.com/google/uuid"
)

// IdempotencyRecord is the model entity for the IdempotencyRecord schema.
type IdempotencyRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID uuid.UUID `json:"public_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int `json:"tenant_id,omitempty"`
	// AgentTokenID holds the value of the "agent_token_id" field.
	AgentTokenID int `json:"agent_token_id,omitempty"`
	// ExperimentID holds the value of the "experiment_id" field.
	ExperimentID int `json:"experiment_id,omitempty"`
	// KeyHash holds the value of the "key_hash" field.
	KeyHash []byte `json:"-"`
	// RequestFingerprint holds the value of the "request_fingerprint" field.
	RequestFingerprint []byte `json:"-"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IdempotencyRecordQuery when eager-loading is set.
	Edges        IdempotencyRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// IdempotencyRecordEdges holds the relations/edges for other nodes in the graph.
type IdempotencyRecordEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// AgentToken holds the value of the agent_token edge.
	AgentToken *AgentToken `json:"agent_token,omitempty"`
	// Experiment holds the value of the experiment edge.
	Experiment *Experiment `json:"experiment,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IdempotencyRecordEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// AgentTokenOrErr returns the AgentToken value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IdempotencyRecordEdges) AgentTokenOrErr() (*AgentToken, error) {
	if e.AgentToken != nil {
		return e.AgentToken, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: agenttoken.Label}
	}
	return nil, &NotLoadedError{edge: "agent_token"}
}

// ExperimentOrErr returns the Experiment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IdempotencyRecordEdges) ExperimentOrErr() (*Experiment, error) {
	if e.Experiment != nil {
		return e.Experiment, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: experiment.Label}
	}
	return nil, &NotLoadedError{edge: "experiment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IdempotencyRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case idempotencyrecord.FieldKeyHash, idempotencyrecord.FieldRequestFingerprint:
			values[i] = new([]byte)
		case idempotencyrecord.FieldID, idempotencyrecord.FieldTenantID, idempotencyrecord.FieldAgentTokenID, idempotencyrecord.FieldExperimentID:
			values[i] = new(sql.NullInt64)
		case idempotencyrecord.FieldCreatedAt, idempotencyrecord.FieldUpdatedAt, idempotencyrecord.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case idempotencyrecord.FieldPublicID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IdempotencyRecord fields.
func (_m *IdempotencyRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case idempotencyrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case idempotencyrecord.FieldPublicID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value != nil {
				_m.PublicID = *value
			}
		case idempotencyrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case idempotencyrecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case idempotencyrecord.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = int(value.Int64)
			}
		case idempotencyrecord.FieldAgentTokenID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field agent_token_id", values[i])
			} else if value.Valid {
				_m.AgentTokenID = int(value.Int64)
			}
		case idempotencyrecord.FieldExperimentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field experiment_id", values[i])
			} else if value.Valid {
				_m.ExperimentID = int(value.Int64)
			}
		case idempotencyrecord.FieldKeyHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field key_hash", values[i])
			} else if value != nil {
				_m.KeyHash = *value
			}
		case idempotencyrecord.FieldRequestFingerprint:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_fingerprint", values[i])
			} else if value != nil {
				_m.RequestFingerprint = *value
			}
		case idempotencyrecord.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IdempotencyRecord.
// This includes values selected through modifiers, order, etc.
func (_m *IdempotencyRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the IdempotencyRecord entity.
func (_m *IdempotencyRecord) QueryTenant() *TenantQuery {
	return NewIdempotencyRecordClient(_m.config).QueryTenant(_m)
}

// QueryAgentToken queries the "agent_token" edge of the IdempotencyRecord entity.
func (_m *IdempotencyRecord) QueryAgentToken() *AgentTokenQuery {
	return NewIdempotencyRecordClient(_m.config).QueryAgentToken(_m)
}

// QueryExperiment queries the "experiment" edge of the IdempotencyRecord entity.
func (_m *IdempotencyRecord) QueryExperiment() *ExperimentQuery {
	return NewIdempotencyRecordClient(_m.config).QueryExperiment(_m)
}

// Update returns a builder for updating this IdempotencyRecord.
// Note that you need to call IdempotencyRecord.Unwrap() before calling this method if this IdempotencyRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IdempotencyRecord) Update() *IdempotencyRecordUpdateOne {
	return NewIdempotencyRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IdempotencyRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IdempotencyRecord) Unwrap() *IdempotencyRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IdempotencyRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IdempotencyRecord) String() string {
	var builder strings.Builder
	builder.WriteString("IdempotencyRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("public_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("agent_token_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AgentTokenID))
	builder.WriteString(", ")
	builder.WriteString("experiment_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExperimentID))
	builder.WriteString(", ")
	builder.WriteString("key_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("request_fingerprint=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// IdempotencyRecords is a parsable slice of IdempotencyRecord.
type IdempotencyRecords []*IdempotencyRecord
