// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/XR-Lee/Gemcp/ent/iterationplan"
	"github.com/XR-Lee/Gemcp/ent/predicate"
)

// IterationPlanDelete is the builder for deleting a IterationPlan entity.
type IterationPlanDelete struct {
	config
	hooks    []Hook
	mutation *IterationPlanMutation
}

// Where appends a list predicates to the IterationPlanDelete builder.
func (_d *IterationPlanDelete) Where(ps ...predicate.IterationPlan) *IterationPlanDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *IterationPlanDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IterationPlanDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *IterationPlanDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(iterationplan.Table, sqlgraph.NewFieldSpec(iterationplan.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// IterationPlanDeleteOne is the builder for deleting a single IterationPlan entity.
type IterationPlanDeleteOne struct {
	_d *IterationPlanDelete
}

// Where appends a list predicates to the IterationPlanDelete builder.
func (_d *IterationPlanDeleteOne) Where(ps ...predicate.IterationPlan) *IterationPlanDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *IterationPlanDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{iterationplan.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IterationPlanDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
