// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/XR-Lee/Gemcp/ent/nodeprojectaccess"
	"github.com/XR-Lee/Gemcp/ent/predicate"
)

// NodeProjectAccessUpdate is the builder for updating NodeProjectAccess entities.
type NodeProjectAccessUpdate struct {
	config
	hooks    []Hook
	mutation *NodeProjectAccessMutation
}

// Where appends a list predicates to the NodeProjectAccessUpdate builder.
func (_u *NodeProjectAccessUpdate) Where(ps ...predicate.NodeProjectAccess) *NodeProjectAccessUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeProjectAccessUpdate) SetUpdatedAt(v time.Time) *NodeProjectAccessUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *NodeProjectAccessUpdate) SetStatus(v nodeprojectaccess.Status) *NodeProjectAccessUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NodeProjectAccessUpdate) SetNillableStatus(v *nodeprojectaccess.Status) *NodeProjectAccessUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the NodeProjectAccessMutation object of the builder.
func (_u *NodeProjectAccessUpdate) Mutation() *NodeProjectAccessMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeProjectAccessUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeProjectAccessUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeProjectAccessUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeProjectAccessUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeProjectAccessUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := nodeprojectaccess.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeProjectAccessUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := nodeprojectaccess.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NodeProjectAccess.status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeProjectAccess.tenant"`)
	}
	if _u.mutation.NodeCleared() && len(_u.mutation.NodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeProjectAccess.node"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeProjectAccess.project"`)
	}
	return nil
}

func (_u *NodeProjectAccessUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nodeprojectaccess.Table, nodeprojectaccess.Columns, sqlgraph.NewFieldSpec(nodeprojectaccess.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(nodeprojectaccess.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(nodeprojectaccess.FieldStatus, field.TypeEnum, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nodeprojectaccess.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeProjectAccessUpdateOne is the builder for updating a single NodeProjectAccess entity.
type NodeProjectAccessUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeProjectAccessMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeProjectAccessUpdateOne) SetUpdatedAt(v time.Time) *NodeProjectAccessUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *NodeProjectAccessUpdateOne) SetStatus(v nodeprojectaccess.Status) *NodeProjectAccessUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NodeProjectAccessUpdateOne) SetNillableStatus(v *nodeprojectaccess.Status) *NodeProjectAccessUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the NodeProjectAccessMutation object of the builder.
func (_u *NodeProjectAccessUpdateOne) Mutation() *NodeProjectAccessMutation {
	return _u.mutation
}

// Where appends a list predicates to the NodeProjectAccessUpdate builder.
func (_u *NodeProjectAccessUpdateOne) Where(ps ...predicate.NodeProjectAccess) *NodeProjectAccessUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeProjectAccessUpdateOne) Select(field string, fields ...string) *NodeProjectAccessUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NodeProjectAccess entity.
func (_u *NodeProjectAccessUpdateOne) Save(ctx context.Context) (*NodeProjectAccess, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeProjectAccessUpdateOne) SaveX(ctx context.Context) *NodeProjectAccess {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeProjectAccessUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeProjectAccessUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeProjectAccessUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := nodeprojectaccess.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeProjectAccessUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := nodeprojectaccess.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NodeProjectAccess.status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeProjectAccess.tenant"`)
	}
	if _u.mutation.NodeCleared() && len(_u.mutation.NodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeProjectAccess.node"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NodeProjectAccess.project"`)
	}
	return nil
}

func (_u *NodeProjectAccessUpdateOne) sqlSave(ctx context.Context) (_node *NodeProjectAccess, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nodeprojectaccess.Table, nodeprojectaccess.Columns, sqlgraph.NewFieldSpec(nodeprojectaccess.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NodeProjectAccess.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nodeprojectaccess.FieldID)
		for _, f := range fields {
			if !nodeprojectaccess.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != nodeprojectaccess.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(nodeprojectaccess.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(nodeprojectaccess.FieldStatus, field.TypeEnum, value)
	}
	_node = &NodeProjectAccess{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nodeprojectaccess.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
