// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/XR-Lee/Gemcp/ent/nodeprojectaccess"
	"github.com/XR-Lee/Gemcp/ent/project"
	"github.com/XR-Lee/Gemcp/ent/selfhostednode"
	"github.com/XR-Lee/Gemcp/ent/tenant"
	"github.com/google/uuid"
)

// NodeProjectAccess is the model entity for the NodeProjectAccess schema.
type NodeProjectAccess struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID uuid.UUID `json:"public_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int `json:"tenant_id,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID int `json:"node_id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID int `json:"project_id,omitempty"`
	// Status holds the value of the "status" field.
	Status nodeprojectaccess.Status `json:"status,omitempty"`
	// ExecutionPolicy holds the value of the "execution_policy" field.
	ExecutionPolicy nodeprojectaccess.ExecutionPolicy `json:"execution_policy,omitempty"`
	// WorkspacePath holds the value of the "workspace_path" field.
	WorkspacePath *string `json:"workspace_path,omitempty"`
	// SuccessfulImages holds the value of the "successful_images" field.
	SuccessfulImages []string `json:"successful_images,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NodeProjectAccessQuery when eager-loading is set.
	Edges        NodeProjectAccessEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NodeProjectAccessEdges holds the relations/edges for other nodes in the graph.
type NodeProjectAccessEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Node holds the value of the node edge.
	Node *SelfHostedNode `json:"node,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeProjectAccessEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// NodeOrErr returns the Node value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeProjectAccessEdges) NodeOrErr() (*SelfHostedNode, error) {
	if e.Node != nil {
		return e.Node, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: selfhostednode.Label}
	}
	return nil, &NotLoadedError{edge: "node"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeProjectAccessEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NodeProjectAccess) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case nodeprojectaccess.FieldSuccessfulImages:
			values[i] = new([]byte)
		case nodeprojectaccess.FieldID, nodeprojectaccess.FieldTenantID, nodeprojectaccess.FieldNodeID, nodeprojectaccess.FieldProjectID:
			values[i] = new(sql.NullInt64)
		case nodeprojectaccess.FieldStatus, nodeprojectaccess.FieldExecutionPolicy, nodeprojectaccess.FieldWorkspacePath:
			values[i] = new(sql.NullString)
		case nodeprojectaccess.FieldCreatedAt, nodeprojectaccess.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case nodeprojectaccess.FieldPublicID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NodeProjectAccess fields.
func (_m *NodeProjectAccess) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nodeprojectaccess.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case nodeprojectaccess.FieldPublicID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value != nil {
				_m.PublicID = *value
			}
		case nodeprojectaccess.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case nodeprojectaccess.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case nodeprojectaccess.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = int(value.Int64)
			}
		case nodeprojectaccess.FieldNodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = int(value.Int64)
			}
		case nodeprojectaccess.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case nodeprojectaccess.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = nodeprojectaccess.Status(value.String)
			}
		case nodeprojectaccess.FieldExecutionPolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_policy", values[i])
			} else if value.Valid {
				_m.ExecutionPolicy = nodeprojectaccess.ExecutionPolicy(value.String)
			}
		case nodeprojectaccess.FieldWorkspacePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_path", values[i])
			} else if value.Valid {
				_m.WorkspacePath = new(string)
				*_m.WorkspacePath = value.String
			}
		case nodeprojectaccess.FieldSuccessfulImages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field successful_images", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SuccessfulImages); err != nil {
					return fmt.Errorf("unmarshal field successful_images: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NodeProjectAccess.
// This includes values selected through modifiers, order, etc.
func (_m *NodeProjectAccess) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the NodeProjectAccess entity.
func (_m *NodeProjectAccess) QueryTenant() *TenantQuery {
	return NewNodeProjectAccessClient(_m.config).QueryTenant(_m)
}

// QueryNode queries the "node" edge of the NodeProjectAccess entity.
func (_m *NodeProjectAccess) QueryNode() *SelfHostedNodeQuery {
	return NewNodeProjectAccessClient(_m.config).QueryNode(_m)
}

// QueryProject queries the "project" edge of the NodeProjectAccess entity.
func (_m *NodeProjectAccess) QueryProject() *ProjectQuery {
	return NewNodeProjectAccessClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this NodeProjectAccess.
// Note that you need to call NodeProjectAccess.Unwrap() before calling this method if this NodeProjectAccess
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NodeProjectAccess) Update() *NodeProjectAccessUpdateOne {
	return NewNodeProjectAccessClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NodeProjectAccess entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NodeProjectAccess) Unwrap() *NodeProjectAccess {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NodeProjectAccess is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NodeProjectAccess) String() string {
	var builder strings.Builder
	builder.WriteString("NodeProjectAccess(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("public_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("node_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("execution_policy=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExecutionPolicy))
	builder.WriteString(", ")
	if v := _m.WorkspacePath; v != nil {
		builder.WriteString("workspace_path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("successful_images=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessfulImages))
	builder.WriteByte(')')
	return builder.String()
}

// NodeProjectAccesses is a parsable slice of NodeProjectAccess.
type NodeProjectAccesses []*NodeProjectAccess
