// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/XR-Lee/Gemcp/ent/predicate"
	"github.com/XR-Lee/Gemcp/ent/researchedge"
)

// ResearchEdgeUpdate is the builder for updating ResearchEdge entities.
type ResearchEdgeUpdate struct {
	config
	hooks    []Hook
	mutation *ResearchEdgeMutation
}

// Where appends a list predicates to the ResearchEdgeUpdate builder.
func (_u *ResearchEdgeUpdate) Where(ps ...predicate.ResearchEdge) *ResearchEdgeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResearchEdgeUpdate) SetUpdatedAt(v time.Time) *ResearchEdgeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ResearchEdgeMutation object of the builder.
func (_u *ResearchEdgeUpdate) Mutation() *ResearchEdgeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResearchEdgeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResearchEdgeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResearchEdgeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResearchEdgeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResearchEdgeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := researchedge.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResearchEdgeUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResearchEdge.tenant"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResearchEdge.project"`)
	}
	if _u.mutation.StudyCleared() && len(_u.mutation.StudyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResearchEdge.study"`)
	}
	if _u.mutation.FromNodeCleared() && len(_u.mutation.FromNodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResearchEdge.from_node"`)
	}
	if _u.mutation.ToNodeCleared() && len(_u.mutation.ToNodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResearchEdge.to_node"`)
	}
	return nil
}

func (_u *ResearchEdgeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(researchedge.Table, researchedge.Columns, sqlgraph.NewFieldSpec(researchedge.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(researchedge.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{researchedge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResearchEdgeUpdateOne is the builder for updating a single ResearchEdge entity.
type ResearchEdgeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResearchEdgeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResearchEdgeUpdateOne) SetUpdatedAt(v time.Time) *ResearchEdgeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ResearchEdgeMutation object of the builder.
func (_u *ResearchEdgeUpdateOne) Mutation() *ResearchEdgeMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResearchEdgeUpdate builder.
func (_u *ResearchEdgeUpdateOne) Where(ps ...predicate.ResearchEdge) *ResearchEdgeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResearchEdgeUpdateOne) Select(field string, fields ...string) *ResearchEdgeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResearchEdge entity.
func (_u *ResearchEdgeUpdateOne) Save(ctx context.Context) (*ResearchEdge, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResearchEdgeUpdateOne) SaveX(ctx context.Context) *ResearchEdge {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResearchEdgeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResearchEdgeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResearchEdgeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := researchedge.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResearchEdgeUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResearchEdge.tenant"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResearchEdge.project"`)
	}
	if _u.mutation.StudyCleared() && len(_u.mutation.StudyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResearchEdge.study"`)
	}
	if _u.mutation.FromNodeCleared() && len(_u.mutation.FromNodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResearchEdge.from_node"`)
	}
	if _u.mutation.ToNodeCleared() && len(_u.mutation.ToNodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResearchEdge.to_node"`)
	}
	return nil
}

func (_u *ResearchEdgeUpdateOne) sqlSave(ctx context.Context) (_node *ResearchEdge, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(researchedge.Table, researchedge.Columns, sqlgraph.NewFieldSpec(researchedge.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResearchEdge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, researchedge.FieldID)
		for _, f := range fields {
			if !researchedge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != researchedge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(researchedge.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ResearchEdge{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{researchedge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
