// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/XR-Lee/Gemcp/ent/experiment"
	"github.com/XR-Lee/Gemcp/ent/project"
	"github.com/XR-Lee/Gemcp/ent/resourceprofile"
	"github.com/google/uuid"
)

// ResourceProfileCreate is the builder for creating a ResourceProfile entity.
type ResourceProfileCreate struct {
	config
	mutation *ResourceProfileMutation
	hooks    []Hook
}

// SetPublicID sets the "public_id" field.
func (_c *ResourceProfileCreate) SetPublicID(v uuid.UUID) *ResourceProfileCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_c *ResourceProfileCreate) SetNillablePublicID(v *uuid.UUID) *ResourceProfileCreate {
	if v != nil {
		_c.SetPublicID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResourceProfileCreate) SetCreatedAt(v time.Time) *ResourceProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResourceProfileCreate) SetNillableCreatedAt(v *time.Time) *ResourceProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResourceProfileCreate) SetUpdatedAt(v time.Time) *ResourceProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResourceProfileCreate) SetNillableUpdatedAt(v *time.Time) *ResourceProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *ResourceProfileCreate) SetProjectID(v int) *ResourceProfileCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetBackend sets the "backend" field.
func (_c *ResourceProfileCreate) SetBackend(v resourceprofile.Backend) *ResourceProfileCreate {
	_c.mutation.SetBackend(v)
	return _c
}

// SetNillableBackend sets the "backend" field if the given value is not nil.
func (_c *ResourceProfileCreate) SetNillableBackend(v *resourceprofile.Backend) *ResourceProfileCreate {
	if v != nil {
		_c.SetBackend(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ResourceProfileCreate) SetName(v string) *ResourceProfileCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRegion sets the "region" field.
func (_c *ResourceProfileCreate) SetRegion(v string) *ResourceProfileCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetGpuNames sets the "gpu_names" field.
func (_c *ResourceProfileCreate) SetGpuNames(v []string) *ResourceProfileCreate {
	_c.mutation.SetGpuNames(v)
	return _c
}

// SetGpuNum sets the "gpu_num" field.
func (_c *ResourceProfileCreate) SetGpuNum(v int) *ResourceProfileCreate {
	_c.mutation.SetGpuNum(v)
	return _c
}

// SetNillableGpuNum sets the "gpu_num" field if the given value is not nil.
func (_c *ResourceProfileCreate) SetNillableGpuNum(v *int) *ResourceProfileCreate {
	if v != nil {
		_c.SetGpuNum(*v)
	}
	return _c
}

// SetCudaFrom sets the "cuda_from" field.
func (_c *ResourceProfileCreate) SetCudaFrom(v int) *ResourceProfileCreate {
	_c.mutation.SetCudaFrom(v)
	return _c
}

// SetCudaTo sets the "cuda_to" field.
func (_c *ResourceProfileCreate) SetCudaTo(v int) *ResourceProfileCreate {
	_c.mutation.SetCudaTo(v)
	return _c
}

// SetCPUFrom sets the "cpu_from" field.
func (_c *ResourceProfileCreate) SetCPUFrom(v int) *ResourceProfileCreate {
	_c.mutation.SetCPUFrom(v)
	return _c
}

// SetCPUTo sets the "cpu_to" field.
func (_c *ResourceProfileCreate) SetCPUTo(v int) *ResourceProfileCreate {
	_c.mutation.SetCPUTo(v)
	return _c
}

// SetMemoryFromGB sets the "memory_from_gb" field.
func (_c *ResourceProfileCreate) SetMemoryFromGB(v int) *ResourceProfileCreate {
	_c.mutation.SetMemoryFromGB(v)
	return _c
}

// SetMemoryToGB sets the "memory_to_gb" field.
func (_c *ResourceProfileCreate) SetMemoryToGB(v int) *ResourceProfileCreate {
	_c.mutation.SetMemoryToGB(v)
	return _c
}

// SetPriceFromMilli sets the "price_from_milli" field.
func (_c *ResourceProfileCreate) SetPriceFromMilli(v int64) *ResourceProfileCreate {
	_c.mutation.SetPriceFromMilli(v)
	return _c
}

// SetPriceToMilli sets the "price_to_milli" field.
func (_c *ResourceProfileCreate) SetPriceToMilli(v int64) *ResourceProfileCreate {
	_c.mutation.SetPriceToMilli(v)
	return _c
}

// SetReuseContainer sets the "reuse_container" field.
func (_c *ResourceProfileCreate) SetReuseContainer(v bool) *ResourceProfileCreate {
	_c.mutation.SetReuseContainer(v)
	return _c
}

// SetNillableReuseContainer sets the "reuse_container" field if the given value is not nil.
func (_c *ResourceProfileCreate) SetNillableReuseContainer(v *bool) *ResourceProfileCreate {
	if v != nil {
		_c.SetReuseContainer(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *ResourceProfileCreate) SetIsDefault(v bool) *ResourceProfileCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *ResourceProfileCreate) SetNillableIsDefault(v *bool) *ResourceProfileCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ResourceProfileCreate) SetStatus(v resourceprofile.Status) *ResourceProfileCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ResourceProfileCreate) SetNillableStatus(v *resourceprofile.Status) *ResourceProfileCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ResourceProfileCreate) SetProject(v *Project) *ResourceProfileCreate {
	return _c.SetProjectID(v.ID)
}

// AddExperimentIDs adds the "experiments" edge to the Experiment entity by IDs.
func (_c *ResourceProfileCreate) AddExperimentIDs(ids ...int) *ResourceProfileCreate {
	_c.mutation.AddExperimentIDs(ids...)
	return _c
}

// AddExperiments adds the "experiments" edges to the Experiment entity.
func (_c *ResourceProfileCreate) AddExperiments(v ...*Experiment) *ResourceProfileCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExperimentIDs(ids...)
}

// Mutation returns the ResourceProfileMutation object of the builder.
func (_c *ResourceProfileCreate) Mutation() *ResourceProfileMutation {
	return _c.mutation
}

// Save creates the ResourceProfile in the database.
func (_c *ResourceProfileCreate) Save(ctx context.Context) (*ResourceProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResourceProfileCreate) SaveX(ctx context.Context) *ResourceProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResourceProfileCreate) defaults() {
	if _, ok := _c.mutation.PublicID(); !ok {
		v := resourceprofile.DefaultPublicID()
		_c.mutation.SetPublicID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resourceprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resourceprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Backend(); !ok {
		v := resourceprofile.DefaultBackend
		_c.mutation.SetBackend(v)
	}
	if _, ok := _c.mutation.GpuNum(); !ok {
		v := resourceprofile.DefaultGpuNum
		_c.mutation.SetGpuNum(v)
	}
	if _, ok := _c.mutation.ReuseContainer(); !ok {
		v := resourceprofile.DefaultReuseContainer
		_c.mutation.SetReuseContainer(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := resourceprofile.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := resourceprofile.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResourceProfileCreate) check() error {
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "ResourceProfile.public_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResourceProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResourceProfile.updated_at"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "ResourceProfile.project_id"`)}
	}
	if _, ok := _c.mutation.Backend(); !ok {
		return &ValidationError{Name: "backend", err: errors.New(`ent: missing required field "ResourceProfile.backend"`)}
	}
	if v, ok := _c.mutation.Backend(); ok {
		if err := resourceprofile.BackendValidator(v); err != nil {
			return &ValidationError{Name: "backend", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.backend": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ResourceProfile.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := resourceprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "ResourceProfile.region"`)}
	}
	if v, ok := _c.mutation.Region(); ok {
		if err := resourceprofile.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.region": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GpuNames(); !ok {
		return &ValidationError{Name: "gpu_names", err: errors.New(`ent: missing required field "ResourceProfile.gpu_names"`)}
	}
	if _, ok := _c.mutation.GpuNum(); !ok {
		return &ValidationError{Name: "gpu_num", err: errors.New(`ent: missing required field "ResourceProfile.gpu_num"`)}
	}
	if v, ok := _c.mutation.GpuNum(); ok {
		if err := resourceprofile.GpuNumValidator(v); err != nil {
			return &ValidationError{Name: "gpu_num", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.gpu_num": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CudaFrom(); !ok {
		return &ValidationError{Name: "cuda_from", err: errors.New(`ent: missing required field "ResourceProfile.cuda_from"`)}
	}
	if v, ok := _c.mutation.CudaFrom(); ok {
		if err := resourceprofile.CudaFromValidator(v); err != nil {
			return &ValidationError{Name: "cuda_from", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.cuda_from": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CudaTo(); !ok {
		return &ValidationError{Name: "cuda_to", err: errors.New(`ent: missing required field "ResourceProfile.cuda_to"`)}
	}
	if v, ok := _c.mutation.CudaTo(); ok {
		if err := resourceprofile.CudaToValidator(v); err != nil {
			return &ValidationError{Name: "cuda_to", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.cuda_to": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CPUFrom(); !ok {
		return &ValidationError{Name: "cpu_from", err: errors.New(`ent: missing required field "ResourceProfile.cpu_from"`)}
	}
	if v, ok := _c.mutation.CPUFrom(); ok {
		if err := resourceprofile.CPUFromValidator(v); err != nil {
			return &ValidationError{Name: "cpu_from", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.cpu_from": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CPUTo(); !ok {
		return &ValidationError{Name: "cpu_to", err: errors.New(`ent: missing required field "ResourceProfile.cpu_to"`)}
	}
	if v, ok := _c.mutation.CPUTo(); ok {
		if err := resourceprofile.CPUToValidator(v); err != nil {
			return &ValidationError{Name: "cpu_to", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.cpu_to": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MemoryFromGB(); !ok {
		return &ValidationError{Name: "memory_from_gb", err: errors.New(`ent: missing required field "ResourceProfile.memory_from_gb"`)}
	}
	if v, ok := _c.mutation.MemoryFromGB(); ok {
		if err := resourceprofile.MemoryFromGBValidator(v); err != nil {
			return &ValidationError{Name: "memory_from_gb", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.memory_from_gb": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MemoryToGB(); !ok {
		return &ValidationError{Name: "memory_to_gb", err: errors.New(`ent: missing required field "ResourceProfile.memory_to_gb"`)}
	}
	if v, ok := _c.mutation.MemoryToGB(); ok {
		if err := resourceprofile.MemoryToGBValidator(v); err != nil {
			return &ValidationError{Name: "memory_to_gb", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.memory_to_gb": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PriceFromMilli(); !ok {
		return &ValidationError{Name: "price_from_milli", err: errors.New(`ent: missing required field "ResourceProfile.price_from_milli"`)}
	}
	if v, ok := _c.mutation.PriceFromMilli(); ok {
		if err := resourceprofile.PriceFromMilliValidator(v); err != nil {
			return &ValidationError{Name: "price_from_milli", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.price_from_milli": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PriceToMilli(); !ok {
		return &ValidationError{Name: "price_to_milli", err: errors.New(`ent: missing required field "ResourceProfile.price_to_milli"`)}
	}
	if v, ok := _c.mutation.PriceToMilli(); ok {
		if err := resourceprofile.PriceToMilliValidator(v); err != nil {
			return &ValidationError{Name: "price_to_milli", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.price_to_milli": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReuseContainer(); !ok {
		return &ValidationError{Name: "reuse_container", err: errors.New(`ent: missing required field "ResourceProfile.reuse_container"`)}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "ResourceProfile.is_default"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ResourceProfile.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := resourceprofile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResourceProfile.status": %w`, err)}
		}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ResourceProfile.project"`)}
	}
	return nil
}

func (_c *ResourceProfileCreate) sqlSave(ctx context.Context) (*ResourceProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResourceProfileCreate) createSpec() (*ResourceProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &ResourceProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resourceprofile.Table, sqlgraph.NewFieldSpec(resourceprofile.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(resourceprofile.FieldPublicID, field.TypeUUID, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resourceprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resourceprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Backend(); ok {
		_spec.SetField(resourceprofile.FieldBackend, field.TypeEnum, value)
		_node.Backend = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(resourceprofile.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(resourceprofile.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.GpuNames(); ok {
		_spec.SetField(resourceprofile.FieldGpuNames, field.TypeJSON, value)
		_node.GpuNames = value
	}
	if value, ok := _c.mutation.GpuNum(); ok {
		_spec.SetField(resourceprofile.FieldGpuNum, field.TypeInt, value)
		_node.GpuNum = value
	}
	if value, ok := _c.mutation.CudaFrom(); ok {
		_spec.SetField(resourceprofile.FieldCudaFrom, field.TypeInt, value)
		_node.CudaFrom = value
	}
	if value, ok := _c.mutation.CudaTo(); ok {
		_spec.SetField(resourceprofile.FieldCudaTo, field.TypeInt, value)
		_node.CudaTo = value
	}
	if value, ok := _c.mutation.CPUFrom(); ok {
		_spec.SetField(resourceprofile.FieldCPUFrom, field.TypeInt, value)
		_node.CPUFrom = value
	}
	if value, ok := _c.mutation.CPUTo(); ok {
		_spec.SetField(resourceprofile.FieldCPUTo, field.TypeInt, value)
		_node.CPUTo = value
	}
	if value, ok := _c.mutation.MemoryFromGB(); ok {
		_spec.SetField(resourceprofile.FieldMemoryFromGB, field.TypeInt, value)
		_node.MemoryFromGB = value
	}
	if value, ok := _c.mutation.MemoryToGB(); ok {
		_spec.SetField(resourceprofile.FieldMemoryToGB, field.TypeInt, value)
		_node.MemoryToGB = value
	}
	if value, ok := _c.mutation.PriceFromMilli(); ok {
		_spec.SetField(resourceprofile.FieldPriceFromMilli, field.TypeInt64, value)
		_node.PriceFromMilli = value
	}
	if value, ok := _c.mutation.PriceToMilli(); ok {
		_spec.SetField(resourceprofile.FieldPriceToMilli, field.TypeInt64, value)
		_node.PriceToMilli = value
	}
	if value, ok := _c.mutation.ReuseContainer(); ok {
		_spec.SetField(resourceprofile.FieldReuseContainer, field.TypeBool, value)
		_node.ReuseContainer = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(resourceprofile.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(resourceprofile.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourceprofile.ProjectTable,
			Columns: []string{resourceprofile.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExperimentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourceprofile.ExperimentsTable,
			Columns: []string{resourceprofile.ExperimentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experiment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ResourceProfileCreateBulk is the builder for creating many ResourceProfile entities in bulk.
type ResourceProfileCreateBulk struct {
	config
	err      error
	builders []*ResourceProfileCreate
}

// Save creates the ResourceProfile entities in the database.
func (_c *ResourceProfileCreateBulk) Save(ctx context.Context) ([]*ResourceProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResourceProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResourceProfileCreateBulk) SaveX(ctx context.Context) []*ResourceProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
