// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/XR-Lee/Gemcp/ent/agenttoken"
	"github.com/XR-Lee/Gemcp/ent/iterationplan"
	"github.com/XR-Lee/Gemcp/ent/project"
	"github.com/XR-Lee/Gemcp/ent/repository"
	"github.com/XR-Lee/Gemcp/ent/researchedge"
	"github.com/XR-Lee/Gemcp/ent/researchnode"
	"github.com/XR-Lee/Gemcp/ent/study"
	"github.com/XR-Lee/Gemcp/ent/tenant"
	"github.com/google/uuid"
)

// StudyCreate is the builder for creating a Study entity.
type StudyCreate struct {
	config
	mutation *StudyMutation
	hooks    []Hook
}

// SetPublicID sets the "public_id" field.
func (_c *StudyCreate) SetPublicID(v uuid.UUID) *StudyCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_c *StudyCreate) SetNillablePublicID(v *uuid.UUID) *StudyCreate {
	if v != nil {
		_c.SetPublicID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StudyCreate) SetCreatedAt(v time.Time) *StudyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StudyCreate) SetNillableCreatedAt(v *time.Time) *StudyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StudyCreate) SetUpdatedAt(v time.Time) *StudyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StudyCreate) SetNillableUpdatedAt(v *time.Time) *StudyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *StudyCreate) SetTenantID(v int) *StudyCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *StudyCreate) SetProjectID(v int) *StudyCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetRepositoryID sets the "repository_id" field.
func (_c *StudyCreate) SetRepositoryID(v int) *StudyCreate {
	_c.mutation.SetRepositoryID(v)
	return _c
}

// SetNillableRepositoryID sets the "repository_id" field if the given value is not nil.
func (_c *StudyCreate) SetNillableRepositoryID(v *int) *StudyCreate {
	if v != nil {
		_c.SetRepositoryID(*v)
	}
	return _c
}

// SetAgentTokenID sets the "agent_token_id" field.
func (_c *StudyCreate) SetAgentTokenID(v int) *StudyCreate {
	_c.mutation.SetAgentTokenID(v)
	return _c
}

// SetNillableAgentTokenID sets the "agent_token_id" field if the given value is not nil.
func (_c *StudyCreate) SetNillableAgentTokenID(v *int) *StudyCreate {
	if v != nil {
		_c.SetAgentTokenID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *StudyCreate) SetName(v string) *StudyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetQuestion sets the "question" field.
func (_c *StudyCreate) SetQuestion(v string) *StudyCreate {
	_c.mutation.SetQuestion(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *StudyCreate) SetSummary(v string) *StudyCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *StudyCreate) SetNillableSummary(v *string) *StudyCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *StudyCreate) SetStatus(v study.Status) *StudyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StudyCreate) SetNillableStatus(v *study.Status) *StudyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProtocolBranch sets the "protocol_branch" field.
func (_c *StudyCreate) SetProtocolBranch(v string) *StudyCreate {
	_c.mutation.SetProtocolBranch(v)
	return _c
}

// SetNillableProtocolBranch sets the "protocol_branch" field if the given value is not nil.
func (_c *StudyCreate) SetNillableProtocolBranch(v *string) *StudyCreate {
	if v != nil {
		_c.SetProtocolBranch(*v)
	}
	return _c
}

// SetProtocolDocPath sets the "protocol_doc_path" field.
func (_c *StudyCreate) SetProtocolDocPath(v string) *StudyCreate {
	_c.mutation.SetProtocolDocPath(v)
	return _c
}

// SetNillableProtocolDocPath sets the "protocol_doc_path" field if the given value is not nil.
func (_c *StudyCreate) SetNillableProtocolDocPath(v *string) *StudyCreate {
	if v != nil {
		_c.SetProtocolDocPath(*v)
	}
	return _c
}

// SetCodeRefPattern sets the "code_ref_pattern" field.
func (_c *StudyCreate) SetCodeRefPattern(v string) *StudyCreate {
	_c.mutation.SetCodeRefPattern(v)
	return _c
}

// SetNillableCodeRefPattern sets the "code_ref_pattern" field if the given value is not nil.
func (_c *StudyCreate) SetNillableCodeRefPattern(v *string) *StudyCreate {
	if v != nil {
		_c.SetCodeRefPattern(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *StudyCreate) SetTenant(v *Tenant) *StudyCreate {
	return _c.SetTenantID(v.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (_c *StudyCreate) SetProject(v *Project) *StudyCreate {
	return _c.SetProjectID(v.ID)
}

// SetRepository sets the "repository" edge to the Repository entity.
func (_c *StudyCreate) SetRepository(v *Repository) *StudyCreate {
	return _c.SetRepositoryID(v.ID)
}

// SetAgentToken sets the "agent_token" edge to the AgentToken entity.
func (_c *StudyCreate) SetAgentToken(v *AgentToken) *StudyCreate {
	return _c.SetAgentTokenID(v.ID)
}

// AddIterationPlanIDs adds the "iteration_plans" edge to the IterationPlan entity by IDs.
func (_c *StudyCreate) AddIterationPlanIDs(ids ...int) *StudyCreate {
	_c.mutation.AddIterationPlanIDs(ids...)
	return _c
}

// AddIterationPlans adds the "iteration_plans" edges to the IterationPlan entity.
func (_c *StudyCreate) AddIterationPlans(v ...*IterationPlan) *StudyCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddIterationPlanIDs(ids...)
}

// AddResearchNodeIDs adds the "research_nodes" edge to the ResearchNode entity by IDs.
func (_c *StudyCreate) AddResearchNodeIDs(ids ...int) *StudyCreate {
	_c.mutation.AddResearchNodeIDs(ids...)
	return _c
}

// AddResearchNodes adds the "research_nodes" edges to the ResearchNode entity.
func (_c *StudyCreate) AddResearchNodes(v ...*ResearchNode) *StudyCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddResearchNodeIDs(ids...)
}

// AddResearchEdgeIDs adds the "research_edges" edge to the ResearchEdge entity by IDs.
func (_c *StudyCreate) AddResearchEdgeIDs(ids ...int) *StudyCreate {
	_c.mutation.AddResearchEdgeIDs(ids...)
	return _c
}

// AddResearchEdges adds the "research_edges" edges to the ResearchEdge entity.
func (_c *StudyCreate) AddResearchEdges(v ...*ResearchEdge) *StudyCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddResearchEdgeIDs(ids...)
}

// Mutation returns the StudyMutation object of the builder.
func (_c *StudyCreate) Mutation() *StudyMutation {
	return _c.mutation
}

// Save creates the Study in the database.
func (_c *StudyCreate) Save(ctx context.Context) (*Study, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StudyCreate) SaveX(ctx context.Context) *Study {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StudyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StudyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StudyCreate) defaults() {
	if _, ok := _c.mutation.PublicID(); !ok {
		v := study.DefaultPublicID()
		_c.mutation.SetPublicID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := study.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := study.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := study.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StudyCreate) check() error {
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "Study.public_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Study.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Study.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Study.tenant_id"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Study.project_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Study.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := study.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Study.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Question(); !ok {
		return &ValidationError{Name: "question", err: errors.New(`ent: missing required field "Study.question"`)}
	}
	if v, ok := _c.mutation.Question(); ok {
		if err := study.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "Study.question": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Study.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := study.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Study.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProtocolBranch(); ok {
		if err := study.ProtocolBranchValidator(v); err != nil {
			return &ValidationError{Name: "protocol_branch", err: fmt.Errorf(`ent: validator failed for field "Study.protocol_branch": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProtocolDocPath(); ok {
		if err := study.ProtocolDocPathValidator(v); err != nil {
			return &ValidationError{Name: "protocol_doc_path", err: fmt.Errorf(`ent: validator failed for field "Study.protocol_doc_path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CodeRefPattern(); ok {
		if err := study.CodeRefPatternValidator(v); err != nil {
			return &ValidationError{Name: "code_ref_pattern", err: fmt.Errorf(`ent: validator failed for field "Study.code_ref_pattern": %w`, err)}
		}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Study.tenant"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Study.project"`)}
	}
	return nil
}

func (_c *StudyCreate) sqlSave(ctx context.Context) (*Study, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StudyCreate) createSpec() (*Study, *sqlgraph.CreateSpec) {
	var (
		_node = &Study{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(study.Table, sqlgraph.NewFieldSpec(study.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(study.FieldPublicID, field.TypeUUID, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(study.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(study.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(study.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Question(); ok {
		_spec.SetField(study.FieldQuestion, field.TypeString, value)
		_node.Question = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(study.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(study.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProtocolBranch(); ok {
		_spec.SetField(study.FieldProtocolBranch, field.TypeString, value)
		_node.ProtocolBranch = value
	}
	if value, ok := _c.mutation.ProtocolDocPath(); ok {
		_spec.SetField(study.FieldProtocolDocPath, field.TypeString, value)
		_node.ProtocolDocPath = value
	}
	if value, ok := _c.mutation.CodeRefPattern(); ok {
		_spec.SetField(study.FieldCodeRefPattern, field.TypeString, value)
		_node.CodeRefPattern = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   study.TenantTable,
			Columns: []string{study.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   study.ProjectTable,
			Columns: []string{study.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RepositoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   study.RepositoryTable,
			Columns: []string{study.RepositoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RepositoryID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   study.AgentTokenTable,
			Columns: []string{study.AgentTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AgentTokenID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.IterationPlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   study.IterationPlansTable,
			Columns: []string{study.IterationPlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(iterationplan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ResearchNodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   study.ResearchNodesTable,
			Columns: []string{study.ResearchNodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchnode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ResearchEdgesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   study.ResearchEdgesTable,
			Columns: []string{study.ResearchEdgesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchedge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StudyCreateBulk is the builder for creating many Study entities in bulk.
type StudyCreateBulk struct {
	config
	err      error
	builders []*StudyCreate
}

// Save creates the Study entities in the database.
func (_c *StudyCreateBulk) Save(ctx context.Context) ([]*Study, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Study, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StudyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StudyCreateBulk) SaveX(ctx context.Context) []*Study {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StudyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StudyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
