// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/XR-Lee/Gemcp/ent/attempt"
	"github.com/XR-Lee/Gemcp/ent/auditevent"
	"github.com/XR-Lee/Gemcp/ent/budgetentry"
	"github.com/XR-Lee/Gemcp/ent/experiment"
	"github.com/XR-Lee/Gemcp/ent/idempotencyrecord"
	"github.com/XR-Lee/Gemcp/ent/nodeassignment"
	"github.com/XR-Lee/Gemcp/ent/nodecommand"
	"github.com/XR-Lee/Gemcp/ent/nodeenrollment"
	"github.com/XR-Lee/Gemcp/ent/nodeevent"
	"github.com/XR-Lee/Gemcp/ent/nodeprojectaccess"
	"github.com/XR-Lee/Gemcp/ent/notification"
	"github.com/XR-Lee/Gemcp/ent/notificationsetting"
	"github.com/XR-Lee/Gemcp/ent/predicate"
	"github.com/XR-Lee/Gemcp/ent/project"
	"github.com/XR-Lee/Gemcp/ent/provideraccount"
	"github.com/XR-Lee/Gemcp/ent/providerresource"
	"github.com/XR-Lee/Gemcp/ent/selfhostednode"
	"github.com/XR-Lee/Gemcp/ent/tenant"
	"github.com/XR-Lee/Gemcp/ent/user"
)

// TenantQuery is the builder for querying Tenant entities.
type TenantQuery struct {
	config
	ctx                      *QueryContext
	order                    []tenant.OrderOption
	inters                   []Interceptor
	predicates               []predicate.Tenant
	withUsers                *UserQuery
	withProviderAccounts     *ProviderAccountQuery
	withProjects             *ProjectQuery
	withExperiments          *ExperimentQuery
	withAttempts             *AttemptQuery
	withProviderResources    *ProviderResourceQuery
	withBudgetEntries        *BudgetEntryQuery
	withIdempotencyRecords   *IdempotencyRecordQuery
	withAuditEvents          *AuditEventQuery
	withNotificationSettings *NotificationSettingQuery
	withNotifications        *NotificationQuery
	withSelfHostedNodes      *SelfHostedNodeQuery
	withNodeEnrollments      *NodeEnrollmentQuery
	withNodeProjectAccess    *NodeProjectAccessQuery
	withNodeCommands         *NodeCommandQuery
	withNodeEvents           *NodeEventQuery
	withNodeAssignments      *NodeAssignmentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TenantQuery builder.
func (_q *TenantQuery) Where(ps ...predicate.Tenant) *TenantQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TenantQuery) Limit(limit int) *TenantQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TenantQuery) Offset(offset int) *TenantQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TenantQuery) Unique(unique bool) *TenantQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TenantQuery) Order(o ...tenant.OrderOption) *TenantQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUsers chains the current query on the "users" edge.
func (_q *TenantQuery) QueryUsers() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.UsersTable, tenant.UsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProviderAccounts chains the current query on the "provider_accounts" edge.
func (_q *TenantQuery) QueryProviderAccounts() *ProviderAccountQuery {
	query := (&ProviderAccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(provideraccount.Table, provideraccount.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.ProviderAccountsTable, tenant.ProviderAccountsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProjects chains the current query on the "projects" edge.
func (_q *TenantQuery) QueryProjects() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.ProjectsTable, tenant.ProjectsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExperiments chains the current query on the "experiments" edge.
func (_q *TenantQuery) QueryExperiments() *ExperimentQuery {
	query := (&ExperimentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(experiment.Table, experiment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.ExperimentsTable, tenant.ExperimentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAttempts chains the current query on the "attempts" edge.
func (_q *TenantQuery) QueryAttempts() *AttemptQuery {
	query := (&AttemptClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(attempt.Table, attempt.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.AttemptsTable, tenant.AttemptsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProviderResources chains the current query on the "provider_resources" edge.
func (_q *TenantQuery) QueryProviderResources() *ProviderResourceQuery {
	query := (&ProviderResourceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(providerresource.Table, providerresource.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.ProviderResourcesTable, tenant.ProviderResourcesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBudgetEntries chains the current query on the "budget_entries" edge.
func (_q *TenantQuery) QueryBudgetEntries() *BudgetEntryQuery {
	query := (&BudgetEntryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(budgetentry.Table, budgetentry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.BudgetEntriesTable, tenant.BudgetEntriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryIdempotencyRecords chains the current query on the "idempotency_records" edge.
func (_q *TenantQuery) QueryIdempotencyRecords() *IdempotencyRecordQuery {
	query := (&IdempotencyRecordClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(idempotencyrecord.Table, idempotencyrecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.IdempotencyRecordsTable, tenant.IdempotencyRecordsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAuditEvents chains the current query on the "audit_events" edge.
func (_q *TenantQuery) QueryAuditEvents() *AuditEventQuery {
	query := (&AuditEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(auditevent.Table, auditevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.AuditEventsTable, tenant.AuditEventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNotificationSettings chains the current query on the "notification_settings" edge.
func (_q *TenantQuery) QueryNotificationSettings() *NotificationSettingQuery {
	query := (&NotificationSettingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(notificationsetting.Table, notificationsetting.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.NotificationSettingsTable, tenant.NotificationSettingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNotifications chains the current query on the "notifications" edge.
func (_q *TenantQuery) QueryNotifications() *NotificationQuery {
	query := (&NotificationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(notification.Table, notification.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.NotificationsTable, tenant.NotificationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySelfHostedNodes chains the current query on the "self_hosted_nodes" edge.
func (_q *TenantQuery) QuerySelfHostedNodes() *SelfHostedNodeQuery {
	query := (&SelfHostedNodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(selfhostednode.Table, selfhostednode.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.SelfHostedNodesTable, tenant.SelfHostedNodesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNodeEnrollments chains the current query on the "node_enrollments" edge.
func (_q *TenantQuery) QueryNodeEnrollments() *NodeEnrollmentQuery {
	query := (&NodeEnrollmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(nodeenrollment.Table, nodeenrollment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.NodeEnrollmentsTable, tenant.NodeEnrollmentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNodeProjectAccess chains the current query on the "node_project_access" edge.
func (_q *TenantQuery) QueryNodeProjectAccess() *NodeProjectAccessQuery {
	query := (&NodeProjectAccessClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(nodeprojectaccess.Table, nodeprojectaccess.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.NodeProjectAccessTable, tenant.NodeProjectAccessColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNodeCommands chains the current query on the "node_commands" edge.
func (_q *TenantQuery) QueryNodeCommands() *NodeCommandQuery {
	query := (&NodeCommandClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(nodecommand.Table, nodecommand.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.NodeCommandsTable, tenant.NodeCommandsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNodeEvents chains the current query on the "node_events" edge.
func (_q *TenantQuery) QueryNodeEvents() *NodeEventQuery {
	query := (&NodeEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(nodeevent.Table, nodeevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.NodeEventsTable, tenant.NodeEventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNodeAssignments chains the current query on the "node_assignments" edge.
func (_q *TenantQuery) QueryNodeAssignments() *NodeAssignmentQuery {
	query := (&NodeAssignmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, selector),
			sqlgraph.To(nodeassignment.Table, nodeassignment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.NodeAssignmentsTable, tenant.NodeAssignmentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Tenant entity from the query.
// Returns a *NotFoundError when no Tenant was found.
func (_q *TenantQuery) First(ctx context.Context) (*Tenant, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tenant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TenantQuery) FirstX(ctx context.Context) *Tenant {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Tenant ID from the query.
// Returns a *NotFoundError when no Tenant ID was found.
func (_q *TenantQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tenant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TenantQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Tenant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Tenant entity is found.
// Returns a *NotFoundError when no Tenant entities are found.
func (_q *TenantQuery) Only(ctx context.Context) (*Tenant, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tenant.Label}
	default:
		return nil, &NotSingularError{tenant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TenantQuery) OnlyX(ctx context.Context) *Tenant {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Tenant ID in the query.
// Returns a *NotSingularError when more than one Tenant ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TenantQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tenant.Label}
	default:
		err = &NotSingularError{tenant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TenantQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Tenants.
func (_q *TenantQuery) All(ctx context.Context) ([]*Tenant, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Tenant, *TenantQuery]()
	return withInterceptors[[]*Tenant](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TenantQuery) AllX(ctx context.Context) []*Tenant {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Tenant IDs.
func (_q *TenantQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(tenant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TenantQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TenantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TenantQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TenantQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TenantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TenantQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TenantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TenantQuery) Clone() *TenantQuery {
	if _q == nil {
		return nil
	}
	return &TenantQuery{
		config:                   _q.config,
		ctx:                      _q.ctx.Clone(),
		order:                    append([]tenant.OrderOption{}, _q.order...),
		inters:                   append([]Interceptor{}, _q.inters...),
		predicates:               append([]predicate.Tenant{}, _q.predicates...),
		withUsers:                _q.withUsers.Clone(),
		withProviderAccounts:     _q.withProviderAccounts.Clone(),
		withProjects:             _q.withProjects.Clone(),
		withExperiments:          _q.withExperiments.Clone(),
		withAttempts:             _q.withAttempts.Clone(),
		withProviderResources:    _q.withProviderResources.Clone(),
		withBudgetEntries:        _q.withBudgetEntries.Clone(),
		withIdempotencyRecords:   _q.withIdempotencyRecords.Clone(),
		withAuditEvents:          _q.withAuditEvents.Clone(),
		withNotificationSettings: _q.withNotificationSettings.Clone(),
		withNotifications:        _q.withNotifications.Clone(),
		withSelfHostedNodes:      _q.withSelfHostedNodes.Clone(),
		withNodeEnrollments:      _q.withNodeEnrollments.Clone(),
		withNodeProjectAccess:    _q.withNodeProjectAccess.Clone(),
		withNodeCommands:         _q.withNodeCommands.Clone(),
		withNodeEvents:           _q.withNodeEvents.Clone(),
		withNodeAssignments:      _q.withNodeAssignments.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithUsers(opts ...func(*UserQuery)) *TenantQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsers = query
	return _q
}

// WithProviderAccounts tells the query-builder to eager-load the nodes that are connected to
// the "provider_accounts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithProviderAccounts(opts ...func(*ProviderAccountQuery)) *TenantQuery {
	query := (&ProviderAccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProviderAccounts = query
	return _q
}

// WithProjects tells the query-builder to eager-load the nodes that are connected to
// the "projects" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithProjects(opts ...func(*ProjectQuery)) *TenantQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProjects = query
	return _q
}

// WithExperiments tells the query-builder to eager-load the nodes that are connected to
// the "experiments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithExperiments(opts ...func(*ExperimentQuery)) *TenantQuery {
	query := (&ExperimentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withExperiments = query
	return _q
}

// WithAttempts tells the query-builder to eager-load the nodes that are connected to
// the "attempts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithAttempts(opts ...func(*AttemptQuery)) *TenantQuery {
	query := (&AttemptClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAttempts = query
	return _q
}

// WithProviderResources tells the query-builder to eager-load the nodes that are connected to
// the "provider_resources" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithProviderResources(opts ...func(*ProviderResourceQuery)) *TenantQuery {
	query := (&ProviderResourceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProviderResources = query
	return _q
}

// WithBudgetEntries tells the query-builder to eager-load the nodes that are connected to
// the "budget_entries" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithBudgetEntries(opts ...func(*BudgetEntryQuery)) *TenantQuery {
	query := (&BudgetEntryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBudgetEntries = query
	return _q
}

// WithIdempotencyRecords tells the query-builder to eager-load the nodes that are connected to
// the "idempotency_records" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithIdempotencyRecords(opts ...func(*IdempotencyRecordQuery)) *TenantQuery {
	query := (&IdempotencyRecordClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withIdempotencyRecords = query
	return _q
}

// WithAuditEvents tells the query-builder to eager-load the nodes that are connected to
// the "audit_events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithAuditEvents(opts ...func(*AuditEventQuery)) *TenantQuery {
	query := (&AuditEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAuditEvents = query
	return _q
}

// WithNotificationSettings tells the query-builder to eager-load the nodes that are connected to
// the "notification_settings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithNotificationSettings(opts ...func(*NotificationSettingQuery)) *TenantQuery {
	query := (&NotificationSettingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNotificationSettings = query
	return _q
}

// WithNotifications tells the query-builder to eager-load the nodes that are connected to
// the "notifications" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithNotifications(opts ...func(*NotificationQuery)) *TenantQuery {
	query := (&NotificationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNotifications = query
	return _q
}

// WithSelfHostedNodes tells the query-builder to eager-load the nodes that are connected to
// the "self_hosted_nodes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithSelfHostedNodes(opts ...func(*SelfHostedNodeQuery)) *TenantQuery {
	query := (&SelfHostedNodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSelfHostedNodes = query
	return _q
}

// WithNodeEnrollments tells the query-builder to eager-load the nodes that are connected to
// the "node_enrollments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithNodeEnrollments(opts ...func(*NodeEnrollmentQuery)) *TenantQuery {
	query := (&NodeEnrollmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNodeEnrollments = query
	return _q
}

// WithNodeProjectAccess tells the query-builder to eager-load the nodes that are connected to
// the "node_project_access" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithNodeProjectAccess(opts ...func(*NodeProjectAccessQuery)) *TenantQuery {
	query := (&NodeProjectAccessClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNodeProjectAccess = query
	return _q
}

// WithNodeCommands tells the query-builder to eager-load the nodes that are connected to
// the "node_commands" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithNodeCommands(opts ...func(*NodeCommandQuery)) *TenantQuery {
	query := (&NodeCommandClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNodeCommands = query
	return _q
}

// WithNodeEvents tells the query-builder to eager-load the nodes that are connected to
// the "node_events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithNodeEvents(opts ...func(*NodeEventQuery)) *TenantQuery {
	query := (&NodeEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNodeEvents = query
	return _q
}

// WithNodeAssignments tells the query-builder to eager-load the nodes that are connected to
// the "node_assignments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TenantQuery) WithNodeAssignments(opts ...func(*NodeAssignmentQuery)) *TenantQuery {
	query := (&NodeAssignmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNodeAssignments = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PublicID uuid.UUID `json:"public_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Tenant.Query().
//		GroupBy(tenant.FieldPublicID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TenantQuery) GroupBy(field string, fields ...string) *TenantGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TenantGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = tenant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PublicID uuid.UUID `json:"public_id,omitempty"`
//	}
//
//	client.Tenant.Query().
//		Select(tenant.FieldPublicID).
//		Scan(ctx, &v)
func (_q *TenantQuery) Select(fields ...string) *TenantSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TenantSelect{TenantQuery: _q}
	sbuild.label = tenant.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TenantSelect configured with the given aggregations.
func (_q *TenantQuery) Aggregate(fns ...AggregateFunc) *TenantSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TenantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !tenant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TenantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Tenant, error) {
	var (
		nodes       = []*Tenant{}
		_spec       = _q.querySpec()
		loadedTypes = [17]bool{
			_q.withUsers != nil,
			_q.withProviderAccounts != nil,
			_q.withProjects != nil,
			_q.withExperiments != nil,
			_q.withAttempts != nil,
			_q.withProviderResources != nil,
			_q.withBudgetEntries != nil,
			_q.withIdempotencyRecords != nil,
			_q.withAuditEvents != nil,
			_q.withNotificationSettings != nil,
			_q.withNotifications != nil,
			_q.withSelfHostedNodes != nil,
			_q.withNodeEnrollments != nil,
			_q.withNodeProjectAccess != nil,
			_q.withNodeCommands != nil,
			_q.withNodeEvents != nil,
			_q.withNodeAssignments != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Tenant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Tenant{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUsers; query != nil {
		if err := _q.loadUsers(ctx, query, nodes,
			func(n *Tenant) { n.Edges.Users = []*User{} },
			func(n *Tenant, e *User) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProviderAccounts; query != nil {
		if err := _q.loadProviderAccounts(ctx, query, nodes,
			func(n *Tenant) { n.Edges.ProviderAccounts = []*ProviderAccount{} },
			func(n *Tenant, e *ProviderAccount) { n.Edges.ProviderAccounts = append(n.Edges.ProviderAccounts, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProjects; query != nil {
		if err := _q.loadProjects(ctx, query, nodes,
			func(n *Tenant) { n.Edges.Projects = []*Project{} },
			func(n *Tenant, e *Project) { n.Edges.Projects = append(n.Edges.Projects, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withExperiments; query != nil {
		if err := _q.loadExperiments(ctx, query, nodes,
			func(n *Tenant) { n.Edges.Experiments = []*Experiment{} },
			func(n *Tenant, e *Experiment) { n.Edges.Experiments = append(n.Edges.Experiments, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAttempts; query != nil {
		if err := _q.loadAttempts(ctx, query, nodes,
			func(n *Tenant) { n.Edges.Attempts = []*Attempt{} },
			func(n *Tenant, e *Attempt) { n.Edges.Attempts = append(n.Edges.Attempts, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProviderResources; query != nil {
		if err := _q.loadProviderResources(ctx, query, nodes,
			func(n *Tenant) { n.Edges.ProviderResources = []*ProviderResource{} },
			func(n *Tenant, e *ProviderResource) { n.Edges.ProviderResources = append(n.Edges.ProviderResources, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBudgetEntries; query != nil {
		if err := _q.loadBudgetEntries(ctx, query, nodes,
			func(n *Tenant) { n.Edges.BudgetEntries = []*BudgetEntry{} },
			func(n *Tenant, e *BudgetEntry) { n.Edges.BudgetEntries = append(n.Edges.BudgetEntries, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withIdempotencyRecords; query != nil {
		if err := _q.loadIdempotencyRecords(ctx, query, nodes,
			func(n *Tenant) { n.Edges.IdempotencyRecords = []*IdempotencyRecord{} },
			func(n *Tenant, e *IdempotencyRecord) {
				n.Edges.IdempotencyRecords = append(n.Edges.IdempotencyRecords, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withAuditEvents; query != nil {
		if err := _q.loadAuditEvents(ctx, query, nodes,
			func(n *Tenant) { n.Edges.AuditEvents = []*AuditEvent{} },
			func(n *Tenant, e *AuditEvent) { n.Edges.AuditEvents = append(n.Edges.AuditEvents, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNotificationSettings; query != nil {
		if err := _q.loadNotificationSettings(ctx, query, nodes,
			func(n *Tenant) { n.Edges.NotificationSettings = []*NotificationSetting{} },
			func(n *Tenant, e *NotificationSetting) {
				n.Edges.NotificationSettings = append(n.Edges.NotificationSettings, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withNotifications; query != nil {
		if err := _q.loadNotifications(ctx, query, nodes,
			func(n *Tenant) { n.Edges.Notifications = []*Notification{} },
			func(n *Tenant, e *Notification) { n.Edges.Notifications = append(n.Edges.Notifications, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSelfHostedNodes; query != nil {
		if err := _q.loadSelfHostedNodes(ctx, query, nodes,
			func(n *Tenant) { n.Edges.SelfHostedNodes = []*SelfHostedNode{} },
			func(n *Tenant, e *SelfHostedNode) { n.Edges.SelfHostedNodes = append(n.Edges.SelfHostedNodes, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNodeEnrollments; query != nil {
		if err := _q.loadNodeEnrollments(ctx, query, nodes,
			func(n *Tenant) { n.Edges.NodeEnrollments = []*NodeEnrollment{} },
			func(n *Tenant, e *NodeEnrollment) { n.Edges.NodeEnrollments = append(n.Edges.NodeEnrollments, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNodeProjectAccess; query != nil {
		if err := _q.loadNodeProjectAccess(ctx, query, nodes,
			func(n *Tenant) { n.Edges.NodeProjectAccess = []*NodeProjectAccess{} },
			func(n *Tenant, e *NodeProjectAccess) {
				n.Edges.NodeProjectAccess = append(n.Edges.NodeProjectAccess, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withNodeCommands; query != nil {
		if err := _q.loadNodeCommands(ctx, query, nodes,
			func(n *Tenant) { n.Edges.NodeCommands = []*NodeCommand{} },
			func(n *Tenant, e *NodeCommand) { n.Edges.NodeCommands = append(n.Edges.NodeCommands, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNodeEvents; query != nil {
		if err := _q.loadNodeEvents(ctx, query, nodes,
			func(n *Tenant) { n.Edges.NodeEvents = []*NodeEvent{} },
			func(n *Tenant, e *NodeEvent) { n.Edges.NodeEvents = append(n.Edges.NodeEvents, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNodeAssignments; query != nil {
		if err := _q.loadNodeAssignments(ctx, query, nodes,
			func(n *Tenant) { n.Edges.NodeAssignments = []*NodeAssignment{} },
			func(n *Tenant, e *NodeAssignment) { n.Edges.NodeAssignments = append(n.Edges.NodeAssignments, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TenantQuery) loadUsers(ctx context.Context, query *UserQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(user.FieldTenantID)
	}
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.UsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadProviderAccounts(ctx context.Context, query *ProviderAccountQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *ProviderAccount)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(provideraccount.FieldTenantID)
	}
	query.Where(predicate.ProviderAccount(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.ProviderAccountsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadProjects(ctx context.Context, query *ProjectQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *Project)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(project.FieldTenantID)
	}
	query.Where(predicate.Project(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.ProjectsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadExperiments(ctx context.Context, query *ExperimentQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *Experiment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(experiment.FieldTenantID)
	}
	query.Where(predicate.Experiment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.ExperimentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadAttempts(ctx context.Context, query *AttemptQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *Attempt)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(attempt.FieldTenantID)
	}
	query.Where(predicate.Attempt(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.AttemptsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadProviderResources(ctx context.Context, query *ProviderResourceQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *ProviderResource)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(providerresource.FieldTenantID)
	}
	query.Where(predicate.ProviderResource(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.ProviderResourcesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadBudgetEntries(ctx context.Context, query *BudgetEntryQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *BudgetEntry)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(budgetentry.FieldTenantID)
	}
	query.Where(predicate.BudgetEntry(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.BudgetEntriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadIdempotencyRecords(ctx context.Context, query *IdempotencyRecordQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *IdempotencyRecord)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(idempotencyrecord.FieldTenantID)
	}
	query.Where(predicate.IdempotencyRecord(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.IdempotencyRecordsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadAuditEvents(ctx context.Context, query *AuditEventQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *AuditEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(auditevent.FieldTenantID)
	}
	query.Where(predicate.AuditEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.AuditEventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadNotificationSettings(ctx context.Context, query *NotificationSettingQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *NotificationSetting)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(notificationsetting.FieldTenantID)
	}
	query.Where(predicate.NotificationSetting(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.NotificationSettingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadNotifications(ctx context.Context, query *NotificationQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *Notification)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(notification.FieldTenantID)
	}
	query.Where(predicate.Notification(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.NotificationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadSelfHostedNodes(ctx context.Context, query *SelfHostedNodeQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *SelfHostedNode)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(selfhostednode.FieldTenantID)
	}
	query.Where(predicate.SelfHostedNode(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.SelfHostedNodesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadNodeEnrollments(ctx context.Context, query *NodeEnrollmentQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *NodeEnrollment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(nodeenrollment.FieldTenantID)
	}
	query.Where(predicate.NodeEnrollment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.NodeEnrollmentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadNodeProjectAccess(ctx context.Context, query *NodeProjectAccessQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *NodeProjectAccess)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(nodeprojectaccess.FieldTenantID)
	}
	query.Where(predicate.NodeProjectAccess(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.NodeProjectAccessColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadNodeCommands(ctx context.Context, query *NodeCommandQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *NodeCommand)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(nodecommand.FieldTenantID)
	}
	query.Where(predicate.NodeCommand(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.NodeCommandsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadNodeEvents(ctx context.Context, query *NodeEventQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *NodeEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(nodeevent.FieldTenantID)
	}
	query.Where(predicate.NodeEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.NodeEventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *TenantQuery) loadNodeAssignments(ctx context.Context, query *NodeAssignmentQuery, nodes []*Tenant, init func(*Tenant), assign func(*Tenant, *NodeAssignment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tenant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(nodeassignment.FieldTenantID)
	}
	query.Where(predicate.NodeAssignment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tenant.NodeAssignmentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *TenantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TenantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for i := range fields {
			if fields[i] != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TenantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(tenant.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = tenant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TenantGroupBy is the group-by builder for Tenant entities.
type TenantGroupBy struct {
	selector
	build *TenantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TenantGroupBy) Aggregate(fns ...AggregateFunc) *TenantGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TenantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TenantQuery, *TenantGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TenantGroupBy) sqlScan(ctx context.Context, root *TenantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TenantSelect is the builder for selecting fields of Tenant entities.
type TenantSelect struct {
	*TenantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TenantSelect) Aggregate(fns ...AggregateFunc) *TenantSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TenantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TenantQuery, *TenantSelect](ctx, _s.TenantQuery, _s, _s.inters, v)
}

func (_s *TenantSelect) sqlScan(ctx context.Context, root *TenantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
