// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/XR-Lee/Gemcp/ent/predicate"
	"github.com/XR-Lee/Gemcp/ent/workspacedataset"
)

// WorkspaceDatasetDelete is the builder for deleting a WorkspaceDataset entity.
type WorkspaceDatasetDelete struct {
	config
	hooks    []Hook
	mutation *WorkspaceDatasetMutation
}

// Where appends a list predicates to the WorkspaceDatasetDelete builder.
func (_d *WorkspaceDatasetDelete) Where(ps ...predicate.WorkspaceDataset) *WorkspaceDatasetDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WorkspaceDatasetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkspaceDatasetDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WorkspaceDatasetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(workspacedataset.Table, sqlgraph.NewFieldSpec(workspacedataset.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WorkspaceDatasetDeleteOne is the builder for deleting a single WorkspaceDataset entity.
type WorkspaceDatasetDeleteOne struct {
	_d *WorkspaceDatasetDelete
}

// Where appends a list predicates to the WorkspaceDatasetDelete builder.
func (_d *WorkspaceDatasetDeleteOne) Where(ps ...predicate.WorkspaceDataset) *WorkspaceDatasetDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WorkspaceDatasetDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workspacedataset.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkspaceDatasetDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
