// Code generated by ent, DO NOT EDIT.

package cloudsshprojectaccess

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/XR-Lee/Gemcp/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldLTE(FieldID, id))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v uuid.UUID) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldPublicID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldTenantID, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldNodeID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldProjectID, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v uuid.UUID) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v uuid.UUID) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...uuid.UUID) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...uuid.UUID) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v uuid.UUID) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v uuid.UUID) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v uuid.UUID) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v uuid.UUID) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldLTE(FieldPublicID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNotIn(FieldTenantID, vs...))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNotIn(FieldNodeID, vs...))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNotIn(FieldProjectID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.FieldNotIn(FieldStatus, vs...))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNode applies the HasEdge predicate on the "node" edge.
func HasNode() predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NodeTable, NodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeWith applies the HasEdge predicate on the "node" edge with a given conditions (other predicates).
func HasNodeWith(preds ...predicate.CloudSSHNode) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(func(s *sql.Selector) {
		step := newNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CloudSSHProjectAccess) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CloudSSHProjectAccess) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CloudSSHProjectAccess) predicate.CloudSSHProjectAccess {
	return predicate.CloudSSHProjectAccess(sql.NotPredicates(p))
}
