// Code generated by ent, DO NOT EDIT.

package projectworkload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the projectworkload type in the database.
	Label = "project_workload"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldSourceExperimentID holds the string denoting the source_experiment_id field in the database.
	FieldSourceExperimentID = "source_experiment_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldManifestYaml holds the string denoting the manifest_yaml field in the database.
	FieldManifestYaml = "manifest_yaml"
	// FieldEntrypoint holds the string denoting the entrypoint field in the database.
	FieldEntrypoint = "entrypoint"
	// FieldRuntimePreset holds the string denoting the runtime_preset field in the database.
	FieldRuntimePreset = "runtime_preset"
	// FieldDataset holds the string denoting the dataset field in the database.
	FieldDataset = "dataset"
	// FieldWorkingDirectory holds the string denoting the working_directory field in the database.
	FieldWorkingDirectory = "working_directory"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeSourceExperiment holds the string denoting the source_experiment edge name in mutations.
	EdgeSourceExperiment = "source_experiment"
	// Table holds the table name of the projectworkload in the database.
	Table = "project_workloads"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "project_workloads"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "project_workloads"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// SourceExperimentTable is the table that holds the source_experiment relation/edge.
	SourceExperimentTable = "project_workloads"
	// SourceExperimentInverseTable is the table name for the Experiment entity.
	// It exists in this package in order to avoid circular dependency with the "experiment" package.
	SourceExperimentInverseTable = "experiments"
	// SourceExperimentColumn is the table column denoting the source_experiment relation/edge.
	SourceExperimentColumn = "source_experiment_id"
)

// Columns holds all SQL columns for projectworkload fields.
var Columns = []string{
	FieldID,
	FieldPublicID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTenantID,
	FieldProjectID,
	FieldSourceExperimentID,
	FieldName,
	FieldManifestYaml,
	FieldEntrypoint,
	FieldRuntimePreset,
	FieldDataset,
	FieldWorkingDirectory,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPublicID holds the default value on creation for the "public_id" field.
	DefaultPublicID func() uuid.UUID
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ManifestYamlValidator is a validator for the "manifest_yaml" field. It is called by the builders before save.
	ManifestYamlValidator func(string) error
	// RuntimePresetValidator is a validator for the "runtime_preset" field. It is called by the builders before save.
	RuntimePresetValidator func(string) error
	// DatasetValidator is a validator for the "dataset" field. It is called by the builders before save.
	DatasetValidator func(string) error
	// WorkingDirectoryValidator is a validator for the "working_directory" field. It is called by the builders before save.
	WorkingDirectoryValidator func(string) error
)

// OrderOption defines the ordering options for the ProjectWorkload queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// BySourceExperimentID orders the results by the source_experiment_id field.
func BySourceExperimentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceExperimentID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByManifestYaml orders the results by the manifest_yaml field.
func ByManifestYaml(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManifestYaml, opts...).ToFunc()
}

// ByRuntimePreset orders the results by the runtime_preset field.
func ByRuntimePreset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuntimePreset, opts...).ToFunc()
}

// ByDataset orders the results by the dataset field.
func ByDataset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataset, opts...).ToFunc()
}

// ByWorkingDirectory orders the results by the working_directory field.
func ByWorkingDirectory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkingDirectory, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceExperimentField orders the results by source_experiment field.
func BySourceExperimentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceExperimentStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newSourceExperimentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceExperimentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, SourceExperimentTable, SourceExperimentColumn),
	)
}
