// Code generated by ent, DO NOT EDIT.

package tenant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/XR-Lee/Gemcp/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Tenant {
	return predicate.Tenant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Tenant {
	return predicate.Tenant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Tenant {
	return predicate.Tenant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Tenant {
	return predicate.Tenant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Tenant {
	return predicate.Tenant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Tenant {
	return predicate.Tenant(sql.FieldLTE(FieldID, id))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v uuid.UUID) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldPublicID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldName, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldStatus, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v uuid.UUID) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v uuid.UUID) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...uuid.UUID) predicate.Tenant {
	return predicate.Tenant(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...uuid.UUID) predicate.Tenant {
	return predicate.Tenant(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v uuid.UUID) predicate.Tenant {
	return predicate.Tenant(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v uuid.UUID) predicate.Tenant {
	return predicate.Tenant(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v uuid.UUID) predicate.Tenant {
	return predicate.Tenant(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v uuid.UUID) predicate.Tenant {
	return predicate.Tenant(sql.FieldLTE(FieldPublicID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Tenant {
	return predicate.Tenant(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Tenant {
	return predicate.Tenant(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Tenant {
	return predicate.Tenant(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Tenant {
	return predicate.Tenant(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldContainsFold(FieldStatus, v))
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.User) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProviderAccounts applies the HasEdge predicate on the "provider_accounts" edge.
func HasProviderAccounts() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProviderAccountsTable, ProviderAccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderAccountsWith applies the HasEdge predicate on the "provider_accounts" edge with a given conditions (other predicates).
func HasProviderAccountsWith(preds ...predicate.ProviderAccount) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newProviderAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProjects applies the HasEdge predicate on the "projects" edge.
func HasProjects() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProjectsTable, ProjectsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectsWith applies the HasEdge predicate on the "projects" edge with a given conditions (other predicates).
func HasProjectsWith(preds ...predicate.Project) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newProjectsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExperiments applies the HasEdge predicate on the "experiments" edge.
func HasExperiments() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExperimentsTable, ExperimentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExperimentsWith applies the HasEdge predicate on the "experiments" edge with a given conditions (other predicates).
func HasExperimentsWith(preds ...predicate.Experiment) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newExperimentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttempts applies the HasEdge predicate on the "attempts" edge.
func HasAttempts() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttemptsTable, AttemptsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttemptsWith applies the HasEdge predicate on the "attempts" edge with a given conditions (other predicates).
func HasAttemptsWith(preds ...predicate.Attempt) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newAttemptsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProviderResources applies the HasEdge predicate on the "provider_resources" edge.
func HasProviderResources() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProviderResourcesTable, ProviderResourcesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderResourcesWith applies the HasEdge predicate on the "provider_resources" edge with a given conditions (other predicates).
func HasProviderResourcesWith(preds ...predicate.ProviderResource) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newProviderResourcesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBudgetEntries applies the HasEdge predicate on the "budget_entries" edge.
func HasBudgetEntries() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BudgetEntriesTable, BudgetEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBudgetEntriesWith applies the HasEdge predicate on the "budget_entries" edge with a given conditions (other predicates).
func HasBudgetEntriesWith(preds ...predicate.BudgetEntry) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newBudgetEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIdempotencyRecords applies the HasEdge predicate on the "idempotency_records" edge.
func HasIdempotencyRecords() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IdempotencyRecordsTable, IdempotencyRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIdempotencyRecordsWith applies the HasEdge predicate on the "idempotency_records" edge with a given conditions (other predicates).
func HasIdempotencyRecordsWith(preds ...predicate.IdempotencyRecord) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newIdempotencyRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuditEvents applies the HasEdge predicate on the "audit_events" edge.
func HasAuditEvents() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AuditEventsTable, AuditEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuditEventsWith applies the HasEdge predicate on the "audit_events" edge with a given conditions (other predicates).
func HasAuditEventsWith(preds ...predicate.AuditEvent) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newAuditEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNotificationSettings applies the HasEdge predicate on the "notification_settings" edge.
func HasNotificationSettings() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NotificationSettingsTable, NotificationSettingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotificationSettingsWith applies the HasEdge predicate on the "notification_settings" edge with a given conditions (other predicates).
func HasNotificationSettingsWith(preds ...predicate.NotificationSetting) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newNotificationSettingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNotifications applies the HasEdge predicate on the "notifications" edge.
func HasNotifications() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NotificationsTable, NotificationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotificationsWith applies the HasEdge predicate on the "notifications" edge with a given conditions (other predicates).
func HasNotificationsWith(preds ...predicate.Notification) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newNotificationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSelfHostedNodes applies the HasEdge predicate on the "self_hosted_nodes" edge.
func HasSelfHostedNodes() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SelfHostedNodesTable, SelfHostedNodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSelfHostedNodesWith applies the HasEdge predicate on the "self_hosted_nodes" edge with a given conditions (other predicates).
func HasSelfHostedNodesWith(preds ...predicate.SelfHostedNode) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newSelfHostedNodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNodeEnrollments applies the HasEdge predicate on the "node_enrollments" edge.
func HasNodeEnrollments() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NodeEnrollmentsTable, NodeEnrollmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeEnrollmentsWith applies the HasEdge predicate on the "node_enrollments" edge with a given conditions (other predicates).
func HasNodeEnrollmentsWith(preds ...predicate.NodeEnrollment) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newNodeEnrollmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNodeProjectAccess applies the HasEdge predicate on the "node_project_access" edge.
func HasNodeProjectAccess() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NodeProjectAccessTable, NodeProjectAccessColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeProjectAccessWith applies the HasEdge predicate on the "node_project_access" edge with a given conditions (other predicates).
func HasNodeProjectAccessWith(preds ...predicate.NodeProjectAccess) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newNodeProjectAccessStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNodeCommands applies the HasEdge predicate on the "node_commands" edge.
func HasNodeCommands() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NodeCommandsTable, NodeCommandsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeCommandsWith applies the HasEdge predicate on the "node_commands" edge with a given conditions (other predicates).
func HasNodeCommandsWith(preds ...predicate.NodeCommand) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newNodeCommandsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNodeEvents applies the HasEdge predicate on the "node_events" edge.
func HasNodeEvents() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NodeEventsTable, NodeEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeEventsWith applies the HasEdge predicate on the "node_events" edge with a given conditions (other predicates).
func HasNodeEventsWith(preds ...predicate.NodeEvent) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newNodeEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNodeAssignments applies the HasEdge predicate on the "node_assignments" edge.
func HasNodeAssignments() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NodeAssignmentsTable, NodeAssignmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNodeAssignmentsWith applies the HasEdge predicate on the "node_assignments" edge with a given conditions (other predicates).
func HasNodeAssignmentsWith(preds ...predicate.NodeAssignment) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newNodeAssignmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDiagnosticRuns applies the HasEdge predicate on the "diagnostic_runs" edge.
func HasDiagnosticRuns() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DiagnosticRunsTable, DiagnosticRunsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDiagnosticRunsWith applies the HasEdge predicate on the "diagnostic_runs" edge with a given conditions (other predicates).
func HasDiagnosticRunsWith(preds ...predicate.DiagnosticRun) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newDiagnosticRunsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExperimentProposals applies the HasEdge predicate on the "experiment_proposals" edge.
func HasExperimentProposals() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExperimentProposalsTable, ExperimentProposalsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExperimentProposalsWith applies the HasEdge predicate on the "experiment_proposals" edge with a given conditions (other predicates).
func HasExperimentProposalsWith(preds ...predicate.ExperimentProposal) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newExperimentProposalsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkspaceDatasets applies the HasEdge predicate on the "workspace_datasets" edge.
func HasWorkspaceDatasets() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WorkspaceDatasetsTable, WorkspaceDatasetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspaceDatasetsWith applies the HasEdge predicate on the "workspace_datasets" edge with a given conditions (other predicates).
func HasWorkspaceDatasetsWith(preds ...predicate.WorkspaceDataset) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newWorkspaceDatasetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStudies applies the HasEdge predicate on the "studies" edge.
func HasStudies() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StudiesTable, StudiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStudiesWith applies the HasEdge predicate on the "studies" edge with a given conditions (other predicates).
func HasStudiesWith(preds ...predicate.Study) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newStudiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIterationPlans applies the HasEdge predicate on the "iteration_plans" edge.
func HasIterationPlans() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IterationPlansTable, IterationPlansColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIterationPlansWith applies the HasEdge predicate on the "iteration_plans" edge with a given conditions (other predicates).
func HasIterationPlansWith(preds ...predicate.IterationPlan) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newIterationPlansStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResearchNodes applies the HasEdge predicate on the "research_nodes" edge.
func HasResearchNodes() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResearchNodesTable, ResearchNodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResearchNodesWith applies the HasEdge predicate on the "research_nodes" edge with a given conditions (other predicates).
func HasResearchNodesWith(preds ...predicate.ResearchNode) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newResearchNodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResearchEdges applies the HasEdge predicate on the "research_edges" edge.
func HasResearchEdges() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResearchEdgesTable, ResearchEdgesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResearchEdgesWith applies the HasEdge predicate on the "research_edges" edge with a given conditions (other predicates).
func HasResearchEdgesWith(preds ...predicate.ResearchEdge) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newResearchEdgesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tenant) predicate.Tenant {
	return predicate.Tenant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tenant) predicate.Tenant {
	return predicate.Tenant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tenant) predicate.Tenant {
	return predicate.Tenant(sql.NotPredicates(p))
}
