// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AgentEnrollment is the predicate function for agentenrollment builders.
type AgentEnrollment func(*sql.Selector)

// AgentToken is the predicate function for agenttoken builders.
type AgentToken func(*sql.Selector)

// Attempt is the predicate function for attempt builders.
type Attempt func(*sql.Selector)

// AuditEvent is the predicate function for auditevent builders.
type AuditEvent func(*sql.Selector)

// BudgetEntry is the predicate function for budgetentry builders.
type BudgetEntry func(*sql.Selector)

// CloudSSHAssignment is the predicate function for cloudsshassignment builders.
type CloudSSHAssignment func(*sql.Selector)

// CloudSSHNode is the predicate function for cloudsshnode builders.
type CloudSSHNode func(*sql.Selector)

// CloudSSHProjectAccess is the predicate function for cloudsshprojectaccess builders.
type CloudSSHProjectAccess func(*sql.Selector)

// DatasetBinding is the predicate function for datasetbinding builders.
type DatasetBinding func(*sql.Selector)

// DiagnosticRun is the predicate function for diagnosticrun builders.
type DiagnosticRun func(*sql.Selector)

// Environment is the predicate function for environment builders.
type Environment func(*sql.Selector)

// Experiment is the predicate function for experiment builders.
type Experiment func(*sql.Selector)

// ExperimentCatalogRow is the predicate function for experimentcatalogrow builders.
type ExperimentCatalogRow func(*sql.Selector)

// ExperimentProposal is the predicate function for experimentproposal builders.
type ExperimentProposal func(*sql.Selector)

// IdempotencyRecord is the predicate function for idempotencyrecord builders.
type IdempotencyRecord func(*sql.Selector)

// ImageBake is the predicate function for imagebake builders.
type ImageBake func(*sql.Selector)

// IterationPlan is the predicate function for iterationplan builders.
type IterationPlan func(*sql.Selector)

// NodeAssignment is the predicate function for nodeassignment builders.
type NodeAssignment func(*sql.Selector)

// NodeCommand is the predicate function for nodecommand builders.
type NodeCommand func(*sql.Selector)

// NodeEnrollment is the predicate function for nodeenrollment builders.
type NodeEnrollment func(*sql.Selector)

// NodeEvent is the predicate function for nodeevent builders.
type NodeEvent func(*sql.Selector)

// NodeProjectAccess is the predicate function for nodeprojectaccess builders.
type NodeProjectAccess func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// NotificationSetting is the predicate function for notificationsetting builders.
type NotificationSetting func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProviderAccount is the predicate function for provideraccount builders.
type ProviderAccount func(*sql.Selector)

// ProviderResource is the predicate function for providerresource builders.
type ProviderResource func(*sql.Selector)

// RecordMixin is the predicate function for recordmixin builders.
type RecordMixin func(*sql.Selector)

// Repository is the predicate function for repository builders.
type Repository func(*sql.Selector)

// ResearchEdge is the predicate function for researchedge builders.
type ResearchEdge func(*sql.Selector)

// ResearchNode is the predicate function for researchnode builders.
type ResearchNode func(*sql.Selector)

// ResourceProfile is the predicate function for resourceprofile builders.
type ResourceProfile func(*sql.Selector)

// SelfHostedNode is the predicate function for selfhostednode builders.
type SelfHostedNode func(*sql.Selector)

// ServiceHeartbeat is the predicate function for serviceheartbeat builders.
type ServiceHeartbeat func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Study is the predicate function for study builders.
type Study func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// WorkspaceDataset is the predicate function for workspacedataset builders.
type WorkspaceDataset func(*sql.Selector)
